/* Auto-generated by scripts/extract_symbols.py */
/* DO NOT EDIT */

#include "stacktrace/symbol.h"

/* String table for symbol names */
__attribute__((section(".rodata")))
const char _symbol_string_table[] =
    "kernel_start\0"
    "halt_loop\0"
    "kernel_main\0"
    "kernel_init\0"
    "isr0\0"
    "isr1\0"
    "isr2\0"
    "isr3\0"
    "isr4\0"
    "isr5\0"
    "isr6\0"
    "isr7\0"
    "isr8\0"
    "isr9\0"
    "isr10\0"
    "isr11\0"
    "isr12\0"
    "isr13\0"
    "isr14\0"
    "isr15\0"
    "isr16\0"
    "isr17\0"
    "isr18\0"
    "isr19\0"
    "isr20\0"
    "isr21\0"
    "isr22\0"
    "isr23\0"
    "isr24\0"
    "isr25\0"
    "isr26\0"
    "isr27\0"
    "isr28\0"
    "isr29\0"
    "isr30\0"
    "isr31\0"
    "irq0\0"
    "irq1\0"
    "irq2\0"
    "irq3\0"
    "irq4\0"
    "irq5\0"
    "irq6\0"
    "irq7\0"
    "irq8\0"
    "irq9\0"
    "irq10\0"
    "irq11\0"
    "irq12\0"
    "irq13\0"
    "irq14\0"
    "irq15\0"
    "interrupt_common\0"
    "idt_load\0"
    "gdt_flush\0"
    "gdt_flush.reload_cs\0"
    "tss_load\0"
    "syscall_handler\0"
    "sysretq\0"
    "int0x80_handler\0"
    "syscall_enable\0"
    "syscall_enable.already_set\0"
    "kvprintf\0"
    "kprintf\0"
    "klog_set_level\0"
    "klog_get_level\0"
    "klog_level_name\0"
    "klog_log\0"
    "klog_init\0"
    "klog_get_backend_ops\0"
    "klog_set_default_backend\0"
    "klog_get_default_backend\0"
    "klog_register_backend\0"
    "serial_is_ready\0"
    "serial_process\0"
    "klog_serial_backend_init\0"
    "klog_serial_backend_get_ops\0"
    "idt_init\0"
    "idt_set_gate\0"
    "idt_set_gate_ist\0"
    "idt_register_handler\0"
    "idt_get_exception_name\0"
    "irq_register_handler\0"
    "irq_unregister_handler\0"
    "interrupt_handler\0"
    "interrupt_init\0"
    "interrupt_finalize\0"
    "tss_init\0"
    "tss_get\0"
    "tss_set_ist_stack\0"
    "tss_get_ist_stack\0"
    "tss_dump\0"
    "gdt_init\0"
    "gdt_get_ptr\0"
    "gdt_dump\0"
    "double_fault_handler\0"
    "gp_fault_handler\0"
    "exception_init\0"
    "exception_get_stats\0"
    "ss_parse_error_code\0"
    "stack_fault_handler\0"
    "gp_parse_error_code\0"
    "syscall_test\0"
    "syscall_debug_log\0"
    "syscall_is_available\0"
    "syscall_init\0"
    "syscall_register_handler\0"
    "syscall_dispatch\0"
    "syscall_dispatch_int80\0"
    "syscall_get_stats\0"
    "syscall_dump_stats\0"
    "sys_getpid\0"
    "sys_getppid\0"
    "sys_read\0"
    "sys_write\0"
    "sys_exit\0"
    "sys_uname\0"
    "sys_close\0"
    "sys_open\0"
    "sys_brk\0"
    "syscall_register_all\0"
    "memset\0"
    "memcpy\0"
    "memmove\0"
    "memcmp\0"
    "vga_update_hardware_cursor_position.part.0\0"
    "vga_scroll.part.0.constprop.0.isra.0\0"
    "vga_enable_cursor\0"
    "vga_set_cursor_color\0"
    "vga_soft_cursor_get\0"
    "vga_soft_cursor_init\0"
    "vga_soft_cursor_enable\0"
    "vga_soft_cursor_hide\0"
    "vga_soft_cursor_draw\0"
    "vga_soft_cursor_update\0"
    "vga_instance\0"
    "system_vga_init\0"
    "vga_clear\0"
    "vga_get_cursor\0"
    "vga_set_cursor\0"
    "vga_print_string\0"
    "vga_print_stringn\0"
    "vga_scroll\0"
    "set_vga_property\0"
    "serial_init\0"
    "sync_serial_puts\0"
    "serial_color_ansi\0"
    "serial_color_for_log_level\0"
    "uart_irq_handler\0"
    "uart_init_intr_mode\0"
    "async_serial_putc\0"
    "async_serial_puts\0"
    "uart_haschar\0"
    "uart_getchar\0"
    "uart_try_getchar\0"
    "uart_set_echo\0"
    "uart_get_echo\0"
    "uart_get_interrupt_count\0"
    "uart_dump_registers\0"
    "keyboard_irq_handler\0"
    "keyboard_init\0"
    "keyboard_haschar\0"
    "keyboard_getchar\0"
    "keyboard_try_getchar\0"
    "keyboard_get_interrupt_count\0"
    "inb\0"
    "outb\0"
    "pic_init\0"
    "pic_send_eoi\0"
    "pic_disable_irq\0"
    "pic_enable_irq\0"
    "pic_is_irq_masked\0"
    "pic_disable_all\0"
    "pic_enable_all\0"
    "timer_irq_handler\0"
    "timer_init\0"
    "timer_get_ticks\0"
    "timer_mdelay\0"
    "timer_set_callback\0"
    "timer_set_frequency\0"
    "rtc_irq_handler\0"
    "rtc_init\0"
    "rtc_enable_periodic\0"
    "rtc_disable_periodic\0"
    "rtc_set_alarm\0"
    "rtc_disable_alarm\0"
    "rtc_get_time\0"
    "rtc_set_time\0"
    "rtc_is_updating\0"
    "rtc_is_valid\0"
    "rtc_get_interrupt_count\0"
    "rtc_format_time\0"
    "kvsnprintf\0"
    "ksnprintf\0"
    "klog_format_string\0"
    "e820_get_stats.part.0\0"
    "e820_init\0"
    "e820_get_detect_method\0"
    "e820_get_detect_method_name\0"
    "e820_get_entry_count\0"
    "e820_get_entry\0"
    "e820_get_stats\0"
    "e820_dump_map\0"
    "e820_is_range_usable\0"
    "e820_find_usable_range\0"
    "e820_get_type_name\0"
    "e820_get_usable_memory_above\0"
    "e820_count_usable_regions\0"
    "format_size.part.0\0"
    "bytes_to_mb\0"
    "bytes_to_kb\0"
    "mb_to_bytes\0"
    "kb_to_bytes\0"
    "pages_to_bytes\0"
    "bytes_to_pages\0"
    "align_up\0"
    "align_down\0"
    "is_aligned\0"
    "format_size\0"
    "format_size_ex\0"
    "format_size_unit\0"
    "mem_summary_init\0"
    "mem_summary_add_region\0"
    "mem_summary_calculate_mb\0"
    "mem_summary_calculate_pages\0"
    "mem_summary_dump\0"
    "ranges_overlap\0"
    "range_contains\0"
    "pframe_init\0"
    "pframe_alloc\0"
    "pframe_alloc_n\0"
    "pframe_free\0"
    "pframe_free_n\0"
    "pframe_get_stats\0"
    "pframe_dump\0"
    "pframe_is_allocated\0"
    "pframe_get_total_frames\0"
    "pframe_get_free_frames\0"
    "eq_cow_block_ptr\0"
    "search_by_phys_iterator\0"
    "hash_cow_block_ptr\0"
    "cow_init\0"
    "cow_is_initialized\0"
    "cow_get_stats\0"
    "cow_inc_refcount\0"
    "cow_add_page\0"
    "cow_dec_refcount\0"
    "cow_get_refcount\0"
    "cow_lookup_block\0"
    "cow_unregister_region\0"
    "cow_mark_page_readonly\0"
    "cow_register_region\0"
    "cow_make_writable\0"
    "cow_copy_on_write\0"
    "cow_handle_fault\0"
    "pf_handler\0"
    "pf_init\0"
    "pf_parse_error_code\0"
    "pf_handle_cow\0"
    "pf_register_cow_region\0"
    "pf_handle_demand_page\0"
    "dump_pte_flags\0"
    "page_init\0"
    "page_get_pml4\0"
    "page_create_table\0"
    "page_free_table\0"
    "page_map_page\0"
    "page_unmap_page\0"
    "page_query\0"
    "page_virt_to_phys\0"
    "page_map_range\0"
    "page_unmap_range\0"
    "page_flush_cache\0"
    "page_dump_mapping\0"
    "page_dump_pml4\0"
    "add_region\0"
    "vmm_init\0"
    "vmm_get_kernel_pml4\0"
    "vmm_get_current_pml4\0"
    "vmm_map_physical\0"
    "vmm_unmap_physical\0"
    "vmm_free_pages\0"
    "vmm_alloc_pages\0"
    "vmm_alloc_pages_at\0"
    "vmm_get_stats\0"
    "vmm_dump\0"
    "vmm_create_user_space\0"
    "vmm_destroy_user_space\0"
    "vmm_map_to_user\0"
    "validate_block\0"
    "insert_to_free_list\0"
    "coalesce_block\0"
    "expand_heap\0"
    "heap_init\0"
    "kmalloc\0"
    "kfree\0"
    "krealloc\0"
    "kmalloc_aligned\0"
    "heap_get_stats\0"
    "heap_dump\0"
    "run_possible_demos\0"
    "test_syscall_stats.isra.0\0"
    "mock_syscall_run_demo\0"
    "mock_syscall_stop_demo\0"
    "ccos_assert_impl\0"
    "assert_backend_to_vga\0"
    "assert_failed_action\0"
    "isspace\0"
    "isdigit\0"
    "strtol\0"
    "strtoll\0"
    "strtoul\0"
    "atoi\0"
    "reverse_str\0"
    "itoa\0"
    "uitoa\0"
    "itoa_signed\0"
    "uitoa64\0"
    "__stack_chk_fail\0"
    "hashmap_create\0"
    "hashmap_destroy\0"
    "hashmap_put\0"
    "hashmap_get\0"
    "hashmap_remove\0"
    "hashmap_size\0"
    "hashmap_contains\0"
    "hashmap_clear\0"
    "hashmap_foreach\0"
    "hash_uint64\0"
    "hash_ptr\0"
    "eq_uint64\0"
    "eq_ptr\0"
    "strlen\0"
    "strnlen\0"
    "strcpy\0"
    "strncpy\0"
    "strcmp\0"
    "strncmp\0"
    "strcasecmp\0"
    "strncasecmp\0"
    "strchr\0"
    "strrchr\0"
    "strstr\0"
    "strpbrk\0"
    "strspn\0"
    "strcspn\0"
    "strtok_r\0"
    "strtok\0"
    "tolower\0"
    "bitmap_init\0"
    "bitmap_set\0"
    "bitmap_clear\0"
    "bitmap_test\0"
    "bitmap_flip\0"
    "bitmap_set_range\0"
    "bitmap_clear_range\0"
    "bitmap_find_first_zero\0"
    "bitmap_find_first_set\0"
    "bitmap_find_next_zero\0"
    "bitmap_find_next_set\0"
    "bitmap_equal\0"
    "bitmap_copy\0"
    "bitmap_and\0"
    "bitmap_or\0"
    "bitmap_xor\0"
    "bitmap_andnot\0"
    "bitmap_complement\0"
    "bitmap_to_string\0"
    "bitmap_weight\0"
    "bitmap_full\0"
    "bitmap_empty\0"
    "isr_handler_table\0"
    "irq_handler_table\0"
    "scancode_to_ascii_shifted\0"
    "scancode_to_ascii_table\0"
    "__func__.0\0"
    "__func__.1\0"
    "__func__.2\0"
    "__func__.3\0"
    "__func__.4\0"
    "__func__.5\0"
    "__func__.6\0"
    "__func__.7\0"
    "__func__.8\0"
    "__func__.9\0"
    "__func__.10\0"
    "uart_echo_enabled\0"
    "s_detect_method\0"
    "s_kernel_virt_hint\0"
    "g_serial_backend_ops\0"
    "exception_names\0"
    "g_ansi_colors\0"
    "uart_irq_desc\0"
    "keyboard_irq_desc\0"
    "timer_irq_desc\0"
    "rtc_irq_desc\0"
    "_GLOBAL_OFFSET_TABLE_\0"
    "buffer.0\0"
    "__bss_start\0"
    "g_log_level\0"
    "buffer\0"
    "g_default_backend\0"
    "g_backend_registry\0"
    "irq_table\0"
    "custom_handlers\0"
    "idt\0"
    "s_initialized\0"
    "s_ist_stacks\0"
    "s_tss\0"
    "s_gdt_ptr\0"
    "s_gdt\0"
    "s_stats\0"
    "s_syscall_table\0"
    "soft_cursor_state\0"
    "internal_vga_instance\0"
    "uart_intr_mode_initialized\0"
    "rx_buffer\0"
    "tx_buffer\0"
    "kb_initialized\0"
    "kb_caps_lock\0"
    "kb_shift_pressed\0"
    "kb_buffer\0"
    "timer_callback\0"
    "timer_frequency\0"
    "timer_ticks\0"
    "rtc_binary_mode\0"
    "rtc_alarm_context\0"
    "rtc_alarm_callback\0"
    "rtc_periodic_context\0"
    "rtc_periodic_callback\0"
    "rtc_interrupt_count\0"
    "g_format_buffer\0"
    "s_e820_entry_count\0"
    "s_e820_entries\0"
    "s_pframe_state\0"
    "s_search_ctx\0"
    "s_cow_state\0"
    "s_pf_stats\0"
    "s_direct_map_established\0"
    "s_kernel_pml4\0"
    "s_region_count\0"
    "s_regions\0"
    "s_heap\0"
    "tests_failed\0"
    "tests_passed\0"
    "save.0\0"
    "s_frame_bitmap_storage\0"
    "__bss_end\0"
;

/* Symbol table entries */
__attribute__((section(".rodata")))
const symbol_entry_t _symbol_table_start[] = {
    { 0x10000, &_symbol_string_table[0] },
    { 0x1003d, &_symbol_string_table[13] },
    { 0x10050, &_symbol_string_table[23] },
    { 0x100c0, &_symbol_string_table[35] },
    { 0x102f0, &_symbol_string_table[47] },
    { 0x102fb, &_symbol_string_table[52] },
    { 0x10306, &_symbol_string_table[57] },
    { 0x10311, &_symbol_string_table[62] },
    { 0x1031c, &_symbol_string_table[67] },
    { 0x10327, &_symbol_string_table[72] },
    { 0x10332, &_symbol_string_table[77] },
    { 0x1033d, &_symbol_string_table[82] },
    { 0x10348, &_symbol_string_table[87] },
    { 0x10351, &_symbol_string_table[92] },
    { 0x1035c, &_symbol_string_table[97] },
    { 0x10365, &_symbol_string_table[103] },
    { 0x1036e, &_symbol_string_table[109] },
    { 0x10377, &_symbol_string_table[115] },
    { 0x10380, &_symbol_string_table[121] },
    { 0x10389, &_symbol_string_table[127] },
    { 0x10394, &_symbol_string_table[133] },
    { 0x1039f, &_symbol_string_table[139] },
    { 0x103aa, &_symbol_string_table[145] },
    { 0x103b5, &_symbol_string_table[151] },
    { 0x103c0, &_symbol_string_table[157] },
    { 0x103cb, &_symbol_string_table[163] },
    { 0x103d6, &_symbol_string_table[169] },
    { 0x103e1, &_symbol_string_table[175] },
    { 0x103ec, &_symbol_string_table[181] },
    { 0x103f7, &_symbol_string_table[187] },
    { 0x10402, &_symbol_string_table[193] },
    { 0x1040d, &_symbol_string_table[199] },
    { 0x10418, &_symbol_string_table[205] },
    { 0x10423, &_symbol_string_table[211] },
    { 0x1042e, &_symbol_string_table[217] },
    { 0x10439, &_symbol_string_table[223] },
    { 0x10444, &_symbol_string_table[229] },
    { 0x1044c, &_symbol_string_table[234] },
    { 0x10454, &_symbol_string_table[239] },
    { 0x1045c, &_symbol_string_table[244] },
    { 0x10464, &_symbol_string_table[249] },
    { 0x1046c, &_symbol_string_table[254] },
    { 0x10474, &_symbol_string_table[259] },
    { 0x1047c, &_symbol_string_table[264] },
    { 0x10484, &_symbol_string_table[269] },
    { 0x1048c, &_symbol_string_table[274] },
    { 0x10494, &_symbol_string_table[279] },
    { 0x1049c, &_symbol_string_table[285] },
    { 0x104a4, &_symbol_string_table[291] },
    { 0x104ac, &_symbol_string_table[297] },
    { 0x104b4, &_symbol_string_table[303] },
    { 0x104bc, &_symbol_string_table[309] },
    { 0x104c4, &_symbol_string_table[315] },
    { 0x1058e, &_symbol_string_table[332] },
    { 0x105a0, &_symbol_string_table[341] },
    { 0x105ba, &_symbol_string_table[351] },
    { 0x105bb, &_symbol_string_table[371] },
    { 0x105d0, &_symbol_string_table[380] },
    { 0x10634, &_symbol_string_table[396] },
    { 0x10634, &_symbol_string_table[404] },
    { 0x10705, &_symbol_string_table[420] },
    { 0x1071a, &_symbol_string_table[435] },
    { 0x10720, &_symbol_string_table[462] },
    { 0x107c0, &_symbol_string_table[471] },
    { 0x10890, &_symbol_string_table[479] },
    { 0x108c0, &_symbol_string_table[494] },
    { 0x108f0, &_symbol_string_table[509] },
    { 0x10980, &_symbol_string_table[525] },
    { 0x10bc0, &_symbol_string_table[534] },
    { 0x10d70, &_symbol_string_table[544] },
    { 0x10df0, &_symbol_string_table[565] },
    { 0x10e20, &_symbol_string_table[590] },
    { 0x10e50, &_symbol_string_table[615] },
    { 0x10fd0, &_symbol_string_table[637] },
    { 0x10fe0, &_symbol_string_table[653] },
    { 0x11050, &_symbol_string_table[668] },
    { 0x11080, &_symbol_string_table[693] },
    { 0x110b0, &_symbol_string_table[721] },
    { 0x11640, &_symbol_string_table[730] },
    { 0x116c0, &_symbol_string_table[743] },
    { 0x11720, &_symbol_string_table[760] },
    { 0x11750, &_symbol_string_table[781] },
    { 0x11790, &_symbol_string_table[804] },
    { 0x11910, &_symbol_string_table[825] },
    { 0x119f0, &_symbol_string_table[848] },
    { 0x11cc0, &_symbol_string_table[866] },
    { 0x11d70, &_symbol_string_table[881] },
    { 0x11df0, &_symbol_string_table[900] },
    { 0x120e0, &_symbol_string_table[909] },
    { 0x12110, &_symbol_string_table[917] },
    { 0x12290, &_symbol_string_table[935] },
    { 0x12380, &_symbol_string_table[953] },
    { 0x12510, &_symbol_string_table[962] },
    { 0x12760, &_symbol_string_table[971] },
    { 0x12790, &_symbol_string_table[983] },
    { 0x12920, &_symbol_string_table[992] },
    { 0x12ba0, &_symbol_string_table[1013] },
    { 0x13050, &_symbol_string_table[1030] },
    { 0x13100, &_symbol_string_table[1045] },
    { 0x13150, &_symbol_string_table[1065] },
    { 0x13270, &_symbol_string_table[1085] },
    { 0x13500, &_symbol_string_table[1105] },
    { 0x13540, &_symbol_string_table[1125] },
    { 0x13550, &_symbol_string_table[1138] },
    { 0x135a0, &_symbol_string_table[1156] },
    { 0x135c0, &_symbol_string_table[1177] },
    { 0x13970, &_symbol_string_table[1190] },
    { 0x13a60, &_symbol_string_table[1215] },
    { 0x13b30, &_symbol_string_table[1232] },
    { 0x13c40, &_symbol_string_table[1255] },
    { 0x13c70, &_symbol_string_table[1273] },
    { 0x13ef0, &_symbol_string_table[1292] },
    { 0x13f00, &_symbol_string_table[1303] },
    { 0x13f10, &_symbol_string_table[1315] },
    { 0x13f20, &_symbol_string_table[1324] },
    { 0x13f90, &_symbol_string_table[1334] },
    { 0x13fe0, &_symbol_string_table[1343] },
    { 0x13ff0, &_symbol_string_table[1353] },
    { 0x14000, &_symbol_string_table[1363] },
    { 0x14010, &_symbol_string_table[1372] },
    { 0x14020, &_symbol_string_table[1380] },
    { 0x141a0, &_symbol_string_table[1401] },
    { 0x142e0, &_symbol_string_table[1408] },
    { 0x143d0, &_symbol_string_table[1415] },
    { 0x14510, &_symbol_string_table[1423] },
    { 0x14560, &_symbol_string_table[1430] },
    { 0x14620, &_symbol_string_table[1473] },
    { 0x14750, &_symbol_string_table[1510] },
    { 0x147e0, &_symbol_string_table[1528] },
    { 0x14860, &_symbol_string_table[1549] },
    { 0x14890, &_symbol_string_table[1569] },
    { 0x14930, &_symbol_string_table[1590] },
    { 0x14ad0, &_symbol_string_table[1613] },
    { 0x14b30, &_symbol_string_table[1634] },
    { 0x14ba0, &_symbol_string_table[1655] },
    { 0x14c80, &_symbol_string_table[1678] },
    { 0x14cb0, &_symbol_string_table[1691] },
    { 0x14d30, &_symbol_string_table[1707] },
    { 0x14e00, &_symbol_string_table[1717] },
    { 0x14e20, &_symbol_string_table[1732] },
    { 0x14e90, &_symbol_string_table[1747] },
    { 0x15240, &_symbol_string_table[1764] },
    { 0x155d0, &_symbol_string_table[1782] },
    { 0x15870, &_symbol_string_table[1793] },
    { 0x15950, &_symbol_string_table[1810] },
    { 0x159e0, &_symbol_string_table[1822] },
    { 0x15a70, &_symbol_string_table[1839] },
    { 0x15ab0, &_symbol_string_table[1857] },
    { 0x15b40, &_symbol_string_table[1884] },
    { 0x15d80, &_symbol_string_table[1901] },
    { 0x15e60, &_symbol_string_table[1921] },
    { 0x16070, &_symbol_string_table[1939] },
    { 0x160e0, &_symbol_string_table[1957] },
    { 0x16120, &_symbol_string_table[1970] },
    { 0x161a0, &_symbol_string_table[1983] },
    { 0x16220, &_symbol_string_table[2000] },
    { 0x16250, &_symbol_string_table[2014] },
    { 0x16280, &_symbol_string_table[2028] },
    { 0x162b0, &_symbol_string_table[2053] },
    { 0x163c0, &_symbol_string_table[2073] },
    { 0x16570, &_symbol_string_table[2094] },
    { 0x16650, &_symbol_string_table[2108] },
    { 0x16690, &_symbol_string_table[2125] },
    { 0x16710, &_symbol_string_table[2142] },
    { 0x16790, &_symbol_string_table[2163] },
    { 0x167c0, &_symbol_string_table[2192] },
    { 0x167d0, &_symbol_string_table[2196] },
    { 0x167e0, &_symbol_string_table[2201] },
    { 0x168c0, &_symbol_string_table[2210] },
    { 0x16920, &_symbol_string_table[2223] },
    { 0x16990, &_symbol_string_table[2239] },
    { 0x16a00, &_symbol_string_table[2254] },
    { 0x16a60, &_symbol_string_table[2272] },
    { 0x16ab0, &_symbol_string_table[2288] },
    { 0x16b00, &_symbol_string_table[2303] },
    { 0x16b50, &_symbol_string_table[2321] },
    { 0x16c60, &_symbol_string_table[2332] },
    { 0x16c90, &_symbol_string_table[2348] },
    { 0x16cf0, &_symbol_string_table[2361] },
    { 0x16d20, &_symbol_string_table[2380] },
    { 0x16df0, &_symbol_string_table[2400] },
    { 0x16ec0, &_symbol_string_table[2416] },
    { 0x170c0, &_symbol_string_table[2425] },
    { 0x17240, &_symbol_string_table[2445] },
    { 0x17330, &_symbol_string_table[2466] },
    { 0x17540, &_symbol_string_table[2480] },
    { 0x17630, &_symbol_string_table[2498] },
    { 0x178b0, &_symbol_string_table[2511] },
    { 0x17c70, &_symbol_string_table[2524] },
    { 0x17cc0, &_symbol_string_table[2540] },
    { 0x17d10, &_symbol_string_table[2553] },
    { 0x17d40, &_symbol_string_table[2577] },
    { 0x17dd0, &_symbol_string_table[2593] },
    { 0x17e00, &_symbol_string_table[2604] },
    { 0x17e60, &_symbol_string_table[2614] },
    { 0x18a00, &_symbol_string_table[2633] },
    { 0x18ac0, &_symbol_string_table[2655] },
    { 0x18d70, &_symbol_string_table[2665] },
    { 0x18da0, &_symbol_string_table[2688] },
    { 0x18e00, &_symbol_string_table[2716] },
    { 0x18e30, &_symbol_string_table[2737] },
    { 0x18ed0, &_symbol_string_table[2752] },
    { 0x18f20, &_symbol_string_table[2767] },
    { 0x192c0, &_symbol_string_table[2781] },
    { 0x19390, &_symbol_string_table[2802] },
    { 0x19490, &_symbol_string_table[2825] },
    { 0x19520, &_symbol_string_table[2844] },
    { 0x195b0, &_symbol_string_table[2873] },
    { 0x19620, &_symbol_string_table[2899] },
    { 0x19700, &_symbol_string_table[2918] },
    { 0x19710, &_symbol_string_table[2930] },
    { 0x19720, &_symbol_string_table[2942] },
    { 0x19730, &_symbol_string_table[2954] },
    { 0x19740, &_symbol_string_table[2966] },
    { 0x19750, &_symbol_string_table[2981] },
    { 0x19760, &_symbol_string_table[2996] },
    { 0x19780, &_symbol_string_table[3005] },
    { 0x19790, &_symbol_string_table[3016] },
    { 0x197b0, &_symbol_string_table[3027] },
    { 0x198a0, &_symbol_string_table[3039] },
    { 0x199d0, &_symbol_string_table[3054] },
    { 0x19af0, &_symbol_string_table[3071] },
    { 0x19b30, &_symbol_string_table[3088] },
    { 0x19b50, &_symbol_string_table[3111] },
    { 0x19b70, &_symbol_string_table[3136] },
    { 0x19ba0, &_symbol_string_table[3164] },
    { 0x19d80, &_symbol_string_table[3181] },
    { 0x19da0, &_symbol_string_table[3196] },
    { 0x19db0, &_symbol_string_table[3211] },
    { 0x1a470, &_symbol_string_table[3223] },
    { 0x1a5d0, &_symbol_string_table[3236] },
    { 0x1a820, &_symbol_string_table[3251] },
    { 0x1a950, &_symbol_string_table[3263] },
    { 0x1aa60, &_symbol_string_table[3277] },
    { 0x1ab00, &_symbol_string_table[3294] },
    { 0x1aca0, &_symbol_string_table[3306] },
    { 0x1ad00, &_symbol_string_table[3326] },
    { 0x1ad30, &_symbol_string_table[3350] },
    { 0x1ada0, &_symbol_string_table[3373] },
    { 0x1adb0, &_symbol_string_table[3390] },
    { 0x1add0, &_symbol_string_table[3414] },
    { 0x1ae00, &_symbol_string_table[3433] },
    { 0x1af30, &_symbol_string_table[3442] },
    { 0x1af60, &_symbol_string_table[3461] },
    { 0x1afe0, &_symbol_string_table[3475] },
    { 0x1b0d0, &_symbol_string_table[3492] },
    { 0x1b200, &_symbol_string_table[3505] },
    { 0x1b300, &_symbol_string_table[3522] },
    { 0x1b3c0, &_symbol_string_table[3539] },
    { 0x1b460, &_symbol_string_table[3556] },
    { 0x1b5d0, &_symbol_string_table[3578] },
    { 0x1b6f0, &_symbol_string_table[3601] },
    { 0x1b900, &_symbol_string_table[3621] },
    { 0x1b9b0, &_symbol_string_table[3639] },
    { 0x1bb40, &_symbol_string_table[3657] },
    { 0x1bd20, &_symbol_string_table[3674] },
    { 0x1c280, &_symbol_string_table[3685] },
    { 0x1c330, &_symbol_string_table[3693] },
    { 0x1c380, &_symbol_string_table[3713] },
    { 0x1c3d0, &_symbol_string_table[3727] },
    { 0x1c410, &_symbol_string_table[3750] },
    { 0x1c440, &_symbol_string_table[3772] },
    { 0x1c670, &_symbol_string_table[3787] },
    { 0x1c870, &_symbol_string_table[3797] },
    { 0x1c8f0, &_symbol_string_table[3811] },
    { 0x1ca10, &_symbol_string_table[3829] },
    { 0x1cad0, &_symbol_string_table[3845] },
    { 0x1d090, &_symbol_string_table[3859] },
    { 0x1d200, &_symbol_string_table[3875] },
    { 0x1d430, &_symbol_string_table[3886] },
    { 0x1d510, &_symbol_string_table[3904] },
    { 0x1d6c0, &_symbol_string_table[3919] },
    { 0x1d780, &_symbol_string_table[3936] },
    { 0x1d7e0, &_symbol_string_table[3953] },
    { 0x1dcf0, &_symbol_string_table[3971] },
    { 0x1df00, &_symbol_string_table[3986] },
    { 0x1dff0, &_symbol_string_table[3997] },
    { 0x1e280, &_symbol_string_table[4006] },
    { 0x1e300, &_symbol_string_table[4026] },
    { 0x1e310, &_symbol_string_table[4047] },
    { 0x1e510, &_symbol_string_table[4064] },
    { 0x1e640, &_symbol_string_table[4083] },
    { 0x1e7e0, &_symbol_string_table[4098] },
    { 0x1eda0, &_symbol_string_table[4114] },
    { 0x1f2b0, &_symbol_string_table[4133] },
    { 0x1f390, &_symbol_string_table[4147] },
    { 0x1f580, &_symbol_string_table[4156] },
    { 0x1f6e0, &_symbol_string_table[4178] },
    { 0x1f9b0, &_symbol_string_table[4201] },
    { 0x1fb60, &_symbol_string_table[4217] },
    { 0x1fc40, &_symbol_string_table[4232] },
    { 0x1fd80, &_symbol_string_table[4252] },
    { 0x20020, &_symbol_string_table[4267] },
    { 0x201f0, &_symbol_string_table[4279] },
    { 0x20380, &_symbol_string_table[4289] },
    { 0x20740, &_symbol_string_table[4297] },
    { 0x20920, &_symbol_string_table[4303] },
    { 0x20c20, &_symbol_string_table[4312] },
    { 0x20da0, &_symbol_string_table[4328] },
    { 0x20fc0, &_symbol_string_table[4343] },
    { 0x21270, &_symbol_string_table[4353] },
    { 0x21350, &_symbol_string_table[4372] },
    { 0x214a0, &_symbol_string_table[4398] },
    { 0x21d20, &_symbol_string_table[4420] },
    { 0x21d70, &_symbol_string_table[4443] },
    { 0x21dc0, &_symbol_string_table[4460] },
    { 0x221f0, &_symbol_string_table[4482] },
    { 0x22240, &_symbol_string_table[4503] },
    { 0x22290, &_symbol_string_table[4511] },
    { 0x222a0, &_symbol_string_table[4519] },
    { 0x22480, &_symbol_string_table[4526] },
    { 0x224b0, &_symbol_string_table[4534] },
    { 0x22660, &_symbol_string_table[4542] },
    { 0x226a0, &_symbol_string_table[4547] },
    { 0x226e0, &_symbol_string_table[4559] },
    { 0x227f0, &_symbol_string_table[4564] },
    { 0x228b0, &_symbol_string_table[4570] },
    { 0x229b0, &_symbol_string_table[4582] },
    { 0x22a80, &_symbol_string_table[4590] },
    { 0x22b00, &_symbol_string_table[4607] },
    { 0x22c70, &_symbol_string_table[4622] },
    { 0x22d30, &_symbol_string_table[4638] },
    { 0x22e20, &_symbol_string_table[4650] },
    { 0x22ea0, &_symbol_string_table[4662] },
    { 0x22f70, &_symbol_string_table[4677] },
    { 0x22f90, &_symbol_string_table[4690] },
    { 0x23010, &_symbol_string_table[4707] },
    { 0x230d0, &_symbol_string_table[4721] },
    { 0x23160, &_symbol_string_table[4737] },
    { 0x23190, &_symbol_string_table[4749] },
    { 0x231a0, &_symbol_string_table[4758] },
    { 0x231b0, &_symbol_string_table[4768] },
    { 0x231c0, &_symbol_string_table[4775] },
    { 0x231f0, &_symbol_string_table[4782] },
    { 0x23230, &_symbol_string_table[4790] },
    { 0x23260, &_symbol_string_table[4797] },
    { 0x232a0, &_symbol_string_table[4805] },
    { 0x232f0, &_symbol_string_table[4812] },
    { 0x23330, &_symbol_string_table[4820] },
    { 0x233e0, &_symbol_string_table[4831] },
    { 0x23450, &_symbol_string_table[4843] },
    { 0x23490, &_symbol_string_table[4850] },
    { 0x234c0, &_symbol_string_table[4858] },
    { 0x23540, &_symbol_string_table[4865] },
    { 0x235a0, &_symbol_string_table[4873] },
    { 0x23600, &_symbol_string_table[4880] },
    { 0x23680, &_symbol_string_table[4888] },
    { 0x23790, &_symbol_string_table[4897] },
    { 0x237c0, &_symbol_string_table[4904] },
    { 0x237e0, &_symbol_string_table[4912] },
    { 0x23820, &_symbol_string_table[4924] },
    { 0x238b0, &_symbol_string_table[4935] },
    { 0x23940, &_symbol_string_table[4948] },
    { 0x239d0, &_symbol_string_table[4960] },
    { 0x23a60, &_symbol_string_table[4972] },
    { 0x23b40, &_symbol_string_table[4989] },
    { 0x23c20, &_symbol_string_table[5008] },
    { 0x23d00, &_symbol_string_table[5031] },
    { 0x23de0, &_symbol_string_table[5053] },
    { 0x23ec0, &_symbol_string_table[5075] },
    { 0x23fa0, &_symbol_string_table[5096] },
    { 0x24010, &_symbol_string_table[5109] },
    { 0x24050, &_symbol_string_table[5121] },
    { 0x240a0, &_symbol_string_table[5132] },
    { 0x240e0, &_symbol_string_table[5142] },
    { 0x24120, &_symbol_string_table[5153] },
    { 0x24160, &_symbol_string_table[5167] },
    { 0x241a0, &_symbol_string_table[5185] },
    { 0x24280, &_symbol_string_table[5202] },
    { 0x24320, &_symbol_string_table[5216] },
    { 0x243d0, &_symbol_string_table[5228] },
    { 0x24480, &_symbol_string_table[5241] },
    { 0x24580, &_symbol_string_table[5259] },
    { 0x24720, &_symbol_string_table[5277] },
    { 0x247a0, &_symbol_string_table[5303] },
    { 0x24a90, &_symbol_string_table[5327] },
    { 0x24aa0, &_symbol_string_table[5338] },
    { 0x24ab0, &_symbol_string_table[5327] },
    { 0x24ac0, &_symbol_string_table[5327] },
    { 0x24ad0, &_symbol_string_table[5338] },
    { 0x24af0, &_symbol_string_table[5349] },
    { 0x24b08, &_symbol_string_table[5360] },
    { 0x24b20, &_symbol_string_table[5371] },
    { 0x24b38, &_symbol_string_table[5382] },
    { 0x24b50, &_symbol_string_table[5393] },
    { 0x24b60, &_symbol_string_table[5404] },
    { 0x24b70, &_symbol_string_table[5415] },
    { 0x24b80, &_symbol_string_table[5426] },
    { 0x24b98, &_symbol_string_table[5437] },
    { 0x24bb0, &_symbol_string_table[5327] },
    { 0x24bc0, &_symbol_string_table[5338] },
    { 0x24be0, &_symbol_string_table[5349] },
    { 0x24bf8, &_symbol_string_table[5360] },
    { 0x24c08, &_symbol_string_table[5371] },
    { 0x24c20, &_symbol_string_table[5382] },
    { 0x24c40, &_symbol_string_table[5393] },
    { 0x24c50, &_symbol_string_table[5404] },
    { 0x24c70, &_symbol_string_table[5415] },
    { 0x24c90, &_symbol_string_table[5426] },
    { 0x24cb0, &_symbol_string_table[5327] },
    { 0x24cc8, &_symbol_string_table[5338] },
    { 0x24ce0, &_symbol_string_table[5349] },
    { 0x24cf8, &_symbol_string_table[5327] },
    { 0x24d08, &_symbol_string_table[5338] },
    { 0x24d18, &_symbol_string_table[5349] },
    { 0x24d28, &_symbol_string_table[5360] },
    { 0x29480, &_symbol_string_table[5449] },
    { 0x29484, &_symbol_string_table[5467] },
    { 0x29488, &_symbol_string_table[5483] },
    { 0x29490, &_symbol_string_table[5502] },
    { 0x294a0, &_symbol_string_table[5523] },
    { 0x295a0, &_symbol_string_table[5539] },
    { 0x29640, &_symbol_string_table[5553] },
    { 0x29680, &_symbol_string_table[5567] },
    { 0x296c0, &_symbol_string_table[5585] },
    { 0x29700, &_symbol_string_table[5600] },
    { 0x29748, &_symbol_string_table[5613] },
    { 0x29760, &_symbol_string_table[5635] },
    { 0x29760, &_symbol_string_table[5644] },
    { 0x29960, &_symbol_string_table[5656] },
    { 0x29980, &_symbol_string_table[5668] },
    { 0x29b80, &_symbol_string_table[5675] },
    { 0x29ba0, &_symbol_string_table[5693] },
    { 0x29c20, &_symbol_string_table[5712] },
    { 0x29d20, &_symbol_string_table[5722] },
    { 0x2a520, &_symbol_string_table[5738] },
    { 0x2b520, &_symbol_string_table[5742] },
    { 0x2b540, &_symbol_string_table[5756] },
    { 0x2b560, &_symbol_string_table[5769] },
    { 0x2b5e0, &_symbol_string_table[5742] },
    { 0x2b5e8, &_symbol_string_table[5775] },
    { 0x2b600, &_symbol_string_table[5785] },
    { 0x2b640, &_symbol_string_table[5635] },
    { 0x2b6c0, &_symbol_string_table[5791] },
    { 0x2b700, &_symbol_string_table[5742] },
    { 0x2b720, &_symbol_string_table[5791] },
    { 0x2bf40, &_symbol_string_table[5799] },
    { 0x2d740, &_symbol_string_table[5815] },
    { 0x2d750, &_symbol_string_table[5833] },
    { 0x2d780, &_symbol_string_table[5855] },
    { 0x2d7a0, &_symbol_string_table[5882] },
    { 0x2d8c0, &_symbol_string_table[5892] },
    { 0x2d9e0, &_symbol_string_table[5902] },
    { 0x2d9e1, &_symbol_string_table[5917] },
    { 0x2d9e2, &_symbol_string_table[5930] },
    { 0x2da00, &_symbol_string_table[5947] },
    { 0x2db08, &_symbol_string_table[5957] },
    { 0x2db10, &_symbol_string_table[5972] },
    { 0x2db18, &_symbol_string_table[5988] },
    { 0x2db20, &_symbol_string_table[6000] },
    { 0x2db28, &_symbol_string_table[6016] },
    { 0x2db30, &_symbol_string_table[6034] },
    { 0x2db38, &_symbol_string_table[6053] },
    { 0x2db40, &_symbol_string_table[6074] },
    { 0x2db48, &_symbol_string_table[6096] },
    { 0x2db60, &_symbol_string_table[6116] },
    { 0x2db80, &_symbol_string_table[5742] },
    { 0x2db84, &_symbol_string_table[6132] },
    { 0x2dba0, &_symbol_string_table[6151] },
    { 0x2e7a0, &_symbol_string_table[6166] },
    { 0x2e7e0, &_symbol_string_table[6181] },
    { 0x2e800, &_symbol_string_table[6194] },
    { 0x2e860, &_symbol_string_table[6206] },
    { 0x2e8a0, &_symbol_string_table[5742] },
    { 0x2e8a4, &_symbol_string_table[6217] },
    { 0x2e8a5, &_symbol_string_table[5742] },
    { 0x2e8a8, &_symbol_string_table[6242] },
    { 0x2e8c0, &_symbol_string_table[5742] },
    { 0x2e8c4, &_symbol_string_table[6256] },
    { 0x2e8e0, &_symbol_string_table[6271] },
    { 0x2f8e0, &_symbol_string_table[5791] },
    { 0x2f908, &_symbol_string_table[6242] },
    { 0x2f920, &_symbol_string_table[6281] },
    { 0x2f990, &_symbol_string_table[6288] },
    { 0x2f994, &_symbol_string_table[6301] },
    { 0x2f998, &_symbol_string_table[6314] },
    { 0x2f9a0, &_symbol_string_table[6321] },
    { 0x2f9a0, &_symbol_string_table[6344] },
    { 0, NULL }
};

__attribute__((section(".rodata")))
const symbol_entry_t _symbol_table_end[] = {
    { 0, NULL }
};

/* Text section bounds */
const uintptr_t _symbol_text_start = 0x10000;
const uintptr_t _symbol_text_end = 0x2447c;
