/**
 * @file symbol.c
 * @brief Symbol table implementation
 * @date 2026-02-17
 */

#include "symbol.h"

// External symbol table generated by scripts/extract_symbols.py
extern const symbol_entry_t _symbol_table_start[];
extern const symbol_entry_t _symbol_table_end[];
extern const char _symbol_string_table[];
extern const uintptr_t _symbol_text_start;
extern const uintptr_t _symbol_text_end;

// Symbol table that references external symbols
// Using non-static and non-const to allow runtime initialization
static symbol_table_t g_symbol_table = {
    .entries = NULL,  // Will be set at runtime
    .count = 0,       // Will be computed at runtime
    .text_start = 0x10000,
    .text_end = 0x20000,
};

// Runtime-computed symbol count
static int g_symbol_count = 0;

static bool g_symbols_initialized = false;

static void init_symbol_table(void) {
    if (g_symbols_initialized) {
        return;
    }

    // Check if we have real symbols (not the placeholder)
    if (_symbol_table_start[0].address != 0) {
        g_symbol_table.entries = _symbol_table_start;

        // Count entries until we hit the terminator
        int count = 0;
        const symbol_entry_t* entry = _symbol_table_start;
        while (entry->address != 0 || entry->name != NULL) {
            count++;
            entry++;
        }
        g_symbol_count = count;
        g_symbol_table.count = count;

        // Use actual text bounds if available
        if (_symbol_text_start != 0) {
            g_symbol_table.text_start = _symbol_text_start;
            g_symbol_table.text_end = _symbol_text_end;
        }
    }

    g_symbols_initialized = true;
}

const symbol_table_t* get_symbol_table(void) {
    init_symbol_table();
    return &g_symbol_table;
}

bool find_symbol(uintptr_t addr, const char** out_name, uintptr_t* out_offset) {
    const symbol_table_t* table = get_symbol_table();

    // No symbols available
    if (table->count == 0) {
        return false;
    }

    // Check if address is in text section
    if (addr < table->text_start || addr >= table->text_end) {
        return false;
    }

    // Binary search for the symbol (table is sorted by address)
    int left = 0;
    int right = table->count - 1;

    while (left <= right) {
        int mid = (left + right) / 2;
        const symbol_entry_t* entry = &table->entries[mid];
        uintptr_t entry_addr = entry->address;
        uintptr_t next_addr = (mid < table->count - 1) ? table->entries[mid + 1].address : 0;

        // Debug: check if name pointer is valid
        if (entry->name == NULL) {
            // Skip entries with NULL names
            right = mid - 1;
            continue;
        }

        if (addr < entry_addr) {
            right = mid - 1;
        } else if (addr >= entry_addr && (mid == table->count - 1 || addr < next_addr)) {
            // Found the symbol - this entry covers our address
            if (out_name) {
                *out_name = entry->name;
            }
            if (out_offset) {
                *out_offset = addr - entry_addr;
            }
            return true;
        } else {
            left = mid + 1;
        }
    }

    return false;
}

void format_symbol(char* buffer, size_t size, uintptr_t addr) {
    const char* name;
    uintptr_t offset;

    if (find_symbol(addr, &name, &offset)) {
        if (offset == 0) {
            // Simple snprintf implementation
            int i = 0;
            while (*name && i < (int)size - 1) {
                buffer[i++] = *name++;
            }
            buffer[i] = '\0';
        } else {
            // Format: "name + 0xoffset"
            int i = 0;
            while (*name && i < (int)size - 20) {
                buffer[i++] = *name++;
            }
            const char* suffix = " + 0x";
            while (*suffix && i < (int)size - 10) {
                buffer[i++] = *suffix++;
            }

            // Convert offset to hex
            uintptr_t val = offset;
            if (val == 0) {
                buffer[i++] = '0';
            } else {
                char hex_rev[20];
                int rev_pos = 0;
                while (val > 0 && rev_pos < 16) {
                    int digit = val & 0xF;
                    hex_rev[rev_pos++] = (digit < 10) ? ('0' + digit) : ('a' + digit - 10);
                    val >>= 4;
                }
                // Reverse
                while (rev_pos > 0 && i < (int)size - 1) {
                    buffer[i++] = hex_rev[--rev_pos];
                }
            }
            buffer[i] = '\0';
        }
    } else {
        // No symbol found, just print address
        int i = 0;
        const char* prefix = "0x";
        while (*prefix && i < (int)size - 1) {
            buffer[i++] = *prefix++;
        }

        // Convert address to hex
        char hex_rev[20];
        int rev_pos = 0;
        uintptr_t val = addr;
        if (val == 0) {
            hex_rev[rev_pos++] = '0';
        } else {
            while (val > 0 && rev_pos < 16) {
                int digit = val & 0xF;
                hex_rev[rev_pos++] = (digit < 10) ? ('0' + digit) : ('a' + digit - 10);
                val >>= 4;
            }
        }
        // Reverse
        while (rev_pos > 0 && i < (int)size - 1) {
            buffer[i++] = hex_rev[--rev_pos];
        }
        buffer[i] = '\0';
    }
}
