/* Auto-generated by scripts/extract_symbols.py */
/* DO NOT EDIT */

#include "stacktrace/symbol.h"

/* String table for symbol names */
__attribute__((section(".rodata")))
const char _symbol_string_table[] =
    "kernel_start\0"
    "halt_loop\0"
    "kernel_main\0"
    "kernel_init\0"
    "isr0\0"
    "isr1\0"
    "isr2\0"
    "isr3\0"
    "isr4\0"
    "isr5\0"
    "isr6\0"
    "isr7\0"
    "isr8\0"
    "isr9\0"
    "isr10\0"
    "isr11\0"
    "isr12\0"
    "isr13\0"
    "isr14\0"
    "isr15\0"
    "isr16\0"
    "isr17\0"
    "isr18\0"
    "isr19\0"
    "isr20\0"
    "isr21\0"
    "isr22\0"
    "isr23\0"
    "isr24\0"
    "isr25\0"
    "isr26\0"
    "isr27\0"
    "isr28\0"
    "isr29\0"
    "isr30\0"
    "isr31\0"
    "irq0\0"
    "irq1\0"
    "irq2\0"
    "irq3\0"
    "irq4\0"
    "irq5\0"
    "irq6\0"
    "irq7\0"
    "irq8\0"
    "irq9\0"
    "irq10\0"
    "irq11\0"
    "irq12\0"
    "irq13\0"
    "irq14\0"
    "irq15\0"
    "interrupt_common\0"
    "idt_load\0"
    "kvprintf\0"
    "kprintf\0"
    "klog_set_level\0"
    "klog_get_level\0"
    "klog_level_name\0"
    "klog_log\0"
    "klog_init\0"
    "klog_get_backend_ops\0"
    "klog_set_default_backend\0"
    "klog_get_default_backend\0"
    "klog_register_backend\0"
    "serial_is_ready\0"
    "serial_process\0"
    "klog_serial_backend_init\0"
    "klog_serial_backend_get_ops\0"
    "bootAllWelcomes\0"
    "vga_display_welcome\0"
    "serial_display_welcome\0"
    "idt_init\0"
    "idt_set_gate\0"
    "idt_register_handler\0"
    "idt_get_exception_name\0"
    "irq_register_handler\0"
    "irq_unregister_handler\0"
    "interrupt_handler\0"
    "interrupt_init\0"
    "interrupt_finalize\0"
    "e820_get_stats.part.0\0"
    "e820_init\0"
    "e820_get_detect_method\0"
    "e820_get_detect_method_name\0"
    "e820_get_entry_count\0"
    "e820_get_entry\0"
    "e820_get_stats\0"
    "e820_dump_map\0"
    "e820_is_range_usable\0"
    "e820_find_usable_range\0"
    "e820_get_type_name\0"
    "e820_get_usable_memory_above\0"
    "e820_count_usable_regions\0"
    "format_size.part.0\0"
    "bytes_to_mb\0"
    "bytes_to_kb\0"
    "mb_to_bytes\0"
    "kb_to_bytes\0"
    "pages_to_bytes\0"
    "bytes_to_pages\0"
    "align_up\0"
    "align_down\0"
    "is_aligned\0"
    "format_size\0"
    "format_size_ex\0"
    "format_size_unit\0"
    "mem_summary_init\0"
    "mem_summary_add_region\0"
    "mem_summary_calculate_mb\0"
    "mem_summary_calculate_pages\0"
    "mem_summary_dump\0"
    "ranges_overlap\0"
    "range_contains\0"
    "memset\0"
    "memcpy\0"
    "memmove\0"
    "memcmp\0"
    "vga_update_hardware_cursor_position.part.0\0"
    "vga_scroll.part.0.constprop.0.isra.0\0"
    "vga_enable_cursor\0"
    "vga_set_cursor_color\0"
    "vga_soft_cursor_get\0"
    "vga_soft_cursor_init\0"
    "vga_soft_cursor_enable\0"
    "vga_soft_cursor_hide\0"
    "vga_soft_cursor_draw\0"
    "vga_soft_cursor_update\0"
    "vga_instance\0"
    "system_vga_init\0"
    "vga_clear\0"
    "vga_get_cursor\0"
    "vga_set_cursor\0"
    "vga_print_string\0"
    "vga_print_stringn\0"
    "vga_scroll\0"
    "set_vga_property\0"
    "vga_delay\0"
    "vga_put_char_at\0"
    "serial_init\0"
    "sync_serial_puts\0"
    "serial_color_ansi\0"
    "serial_color_for_log_level\0"
    "uart_irq_handler\0"
    "uart_init_intr_mode\0"
    "async_serial_putc\0"
    "async_serial_puts\0"
    "uart_haschar\0"
    "uart_getchar\0"
    "uart_try_getchar\0"
    "uart_set_echo\0"
    "uart_get_echo\0"
    "uart_get_interrupt_count\0"
    "uart_dump_registers\0"
    "keyboard_irq_handler\0"
    "keyboard_init\0"
    "keyboard_haschar\0"
    "keyboard_getchar\0"
    "keyboard_try_getchar\0"
    "keyboard_get_interrupt_count\0"
    "inb\0"
    "outb\0"
    "pic_init\0"
    "pic_send_eoi\0"
    "pic_disable_irq\0"
    "pic_enable_irq\0"
    "pic_is_irq_masked\0"
    "pic_disable_all\0"
    "pic_enable_all\0"
    "timer_irq_handler\0"
    "timer_init\0"
    "timer_get_ticks\0"
    "timer_mdelay\0"
    "timer_set_callback\0"
    "timer_set_frequency\0"
    "rtc_irq_handler\0"
    "rtc_init\0"
    "rtc_enable_periodic\0"
    "rtc_disable_periodic\0"
    "rtc_set_alarm\0"
    "rtc_disable_alarm\0"
    "rtc_get_time\0"
    "rtc_set_time\0"
    "rtc_is_updating\0"
    "rtc_is_valid\0"
    "rtc_get_interrupt_count\0"
    "rtc_format_time\0"
    "kvsnprintf\0"
    "ksnprintf\0"
    "klog_format_string\0"
    "isspace\0"
    "isdigit\0"
    "strtol\0"
    "strtoll\0"
    "strtoul\0"
    "atoi\0"
    "reverse_str\0"
    "itoa\0"
    "uitoa\0"
    "itoa_signed\0"
    "uitoa64\0"
    "strlen\0"
    "strnlen\0"
    "strcpy\0"
    "strncpy\0"
    "strcmp\0"
    "strncmp\0"
    "strcasecmp\0"
    "strncasecmp\0"
    "strchr\0"
    "strrchr\0"
    "strstr\0"
    "strpbrk\0"
    "strspn\0"
    "strcspn\0"
    "strtok_r\0"
    "strtok\0"
    "tolower\0"
    "run_possible_demos\0"
    "vga_clear_screen\0"
    "cmd_cls\0"
    "vga_getchar\0"
    "vga_haschar\0"
    "vga_putc\0"
    "cmd_ticks\0"
    "cmd_time\0"
    "cmd_keyboard\0"
    "cmd_goto\0"
    "cmd_color\0"
    "vga_puts\0"
    "vga_shell_init\0"
    "vga_shell_backend_get\0"
    "vga_shell_run\0"
    "vga_shell_init_commands\0"
    "cmd_clear\0"
    "cmd_exit\0"
    "cmd_help\0"
    "shell_step.part.0\0"
    "shell_create\0"
    "shell_step\0"
    "shell_run\0"
    "shell_destroy\0"
    "shell_register_command\0"
    "shell_unregister_command\0"
    "isr_handler_table\0"
    "irq_handler_table\0"
    "scancode_to_ascii_shifted\0"
    "scancode_to_ascii_table\0"
    "s_detect_method\0"
    "uart_echo_enabled\0"
    "g_serial_backend_ops\0"
    "CCOS_LOGO\0"
    "exception_names\0"
    "g_ansi_colors\0"
    "uart_irq_desc\0"
    "keyboard_irq_desc\0"
    "timer_irq_desc\0"
    "rtc_irq_desc\0"
    "g_vga_backend\0"
    "_GLOBAL_OFFSET_TABLE_\0"
    "buffer.0\0"
    "__bss_start\0"
    "g_log_level\0"
    "buffer\0"
    "g_default_backend\0"
    "g_backend_registry\0"
    "irq_table\0"
    "custom_handlers\0"
    "idt\0"
    "s_initialized\0"
    "s_e820_entry_count\0"
    "s_e820_entries\0"
    "soft_cursor_state\0"
    "internal_vga_instance\0"
    "uart_intr_mode_initialized\0"
    "rx_buffer\0"
    "tx_buffer\0"
    "kb_initialized\0"
    "kb_caps_lock\0"
    "kb_shift_pressed\0"
    "kb_buffer\0"
    "timer_callback\0"
    "timer_frequency\0"
    "timer_ticks\0"
    "rtc_binary_mode\0"
    "rtc_alarm_context\0"
    "rtc_alarm_callback\0"
    "rtc_periodic_context\0"
    "rtc_periodic_callback\0"
    "rtc_interrupt_count\0"
    "g_format_buffer\0"
    "save.0\0"
    "registered.0\0"
    "g_shell_ctx.1\0"
    "g_command_count\0"
    "g_commands\0"
    "__bss_end\0"
;

/* Symbol table entries */
__attribute__((section(".rodata")))
const symbol_entry_t _symbol_table_start[] = {
    { 0x10000, &_symbol_string_table[0] },
    { 0x1003d, &_symbol_string_table[13] },
    { 0x10050, &_symbol_string_table[23] },
    { 0x100d0, &_symbol_string_table[35] },
    { 0x10290, &_symbol_string_table[47] },
    { 0x1029b, &_symbol_string_table[52] },
    { 0x102a6, &_symbol_string_table[57] },
    { 0x102b1, &_symbol_string_table[62] },
    { 0x102bc, &_symbol_string_table[67] },
    { 0x102c7, &_symbol_string_table[72] },
    { 0x102d2, &_symbol_string_table[77] },
    { 0x102dd, &_symbol_string_table[82] },
    { 0x102e8, &_symbol_string_table[87] },
    { 0x102f1, &_symbol_string_table[92] },
    { 0x102fc, &_symbol_string_table[97] },
    { 0x10305, &_symbol_string_table[103] },
    { 0x1030e, &_symbol_string_table[109] },
    { 0x10317, &_symbol_string_table[115] },
    { 0x10320, &_symbol_string_table[121] },
    { 0x10329, &_symbol_string_table[127] },
    { 0x10334, &_symbol_string_table[133] },
    { 0x1033f, &_symbol_string_table[139] },
    { 0x1034a, &_symbol_string_table[145] },
    { 0x10355, &_symbol_string_table[151] },
    { 0x10360, &_symbol_string_table[157] },
    { 0x1036b, &_symbol_string_table[163] },
    { 0x10376, &_symbol_string_table[169] },
    { 0x10381, &_symbol_string_table[175] },
    { 0x1038c, &_symbol_string_table[181] },
    { 0x10397, &_symbol_string_table[187] },
    { 0x103a2, &_symbol_string_table[193] },
    { 0x103ad, &_symbol_string_table[199] },
    { 0x103b8, &_symbol_string_table[205] },
    { 0x103c3, &_symbol_string_table[211] },
    { 0x103ce, &_symbol_string_table[217] },
    { 0x103d9, &_symbol_string_table[223] },
    { 0x103e4, &_symbol_string_table[229] },
    { 0x103ec, &_symbol_string_table[234] },
    { 0x103f4, &_symbol_string_table[239] },
    { 0x103fc, &_symbol_string_table[244] },
    { 0x10404, &_symbol_string_table[249] },
    { 0x1040c, &_symbol_string_table[254] },
    { 0x10414, &_symbol_string_table[259] },
    { 0x1041c, &_symbol_string_table[264] },
    { 0x10424, &_symbol_string_table[269] },
    { 0x1042c, &_symbol_string_table[274] },
    { 0x10434, &_symbol_string_table[279] },
    { 0x1043c, &_symbol_string_table[285] },
    { 0x10444, &_symbol_string_table[291] },
    { 0x1044c, &_symbol_string_table[297] },
    { 0x10454, &_symbol_string_table[303] },
    { 0x1045c, &_symbol_string_table[309] },
    { 0x10464, &_symbol_string_table[315] },
    { 0x1052e, &_symbol_string_table[332] },
    { 0x10540, &_symbol_string_table[341] },
    { 0x105e0, &_symbol_string_table[350] },
    { 0x106b0, &_symbol_string_table[358] },
    { 0x106e0, &_symbol_string_table[373] },
    { 0x10710, &_symbol_string_table[388] },
    { 0x107a0, &_symbol_string_table[404] },
    { 0x109e0, &_symbol_string_table[413] },
    { 0x10b90, &_symbol_string_table[423] },
    { 0x10c10, &_symbol_string_table[444] },
    { 0x10c40, &_symbol_string_table[469] },
    { 0x10c70, &_symbol_string_table[494] },
    { 0x10df0, &_symbol_string_table[516] },
    { 0x10e00, &_symbol_string_table[532] },
    { 0x10e70, &_symbol_string_table[547] },
    { 0x10ea0, &_symbol_string_table[572] },
    { 0x10ed0, &_symbol_string_table[600] },
    { 0x10f50, &_symbol_string_table[616] },
    { 0x11380, &_symbol_string_table[636] },
    { 0x11d00, &_symbol_string_table[659] },
    { 0x12250, &_symbol_string_table[668] },
    { 0x122d0, &_symbol_string_table[681] },
    { 0x12300, &_symbol_string_table[702] },
    { 0x12340, &_symbol_string_table[725] },
    { 0x124c0, &_symbol_string_table[746] },
    { 0x125a0, &_symbol_string_table[769] },
    { 0x12870, &_symbol_string_table[787] },
    { 0x12920, &_symbol_string_table[802] },
    { 0x129c0, &_symbol_string_table[821] },
    { 0x12a80, &_symbol_string_table[843] },
    { 0x12df0, &_symbol_string_table[853] },
    { 0x12e20, &_symbol_string_table[876] },
    { 0x12e80, &_symbol_string_table[904] },
    { 0x12eb0, &_symbol_string_table[925] },
    { 0x12f50, &_symbol_string_table[940] },
    { 0x12fa0, &_symbol_string_table[955] },
    { 0x13340, &_symbol_string_table[969] },
    { 0x13410, &_symbol_string_table[990] },
    { 0x13510, &_symbol_string_table[1013] },
    { 0x135a0, &_symbol_string_table[1032] },
    { 0x13630, &_symbol_string_table[1061] },
    { 0x136a0, &_symbol_string_table[1087] },
    { 0x13780, &_symbol_string_table[1106] },
    { 0x13790, &_symbol_string_table[1118] },
    { 0x137a0, &_symbol_string_table[1130] },
    { 0x137b0, &_symbol_string_table[1142] },
    { 0x137c0, &_symbol_string_table[1154] },
    { 0x137d0, &_symbol_string_table[1169] },
    { 0x137e0, &_symbol_string_table[1184] },
    { 0x13800, &_symbol_string_table[1193] },
    { 0x13810, &_symbol_string_table[1204] },
    { 0x13830, &_symbol_string_table[1215] },
    { 0x13920, &_symbol_string_table[1227] },
    { 0x13a50, &_symbol_string_table[1242] },
    { 0x13b70, &_symbol_string_table[1259] },
    { 0x13bb0, &_symbol_string_table[1276] },
    { 0x13bd0, &_symbol_string_table[1299] },
    { 0x13bf0, &_symbol_string_table[1324] },
    { 0x13c20, &_symbol_string_table[1352] },
    { 0x13e00, &_symbol_string_table[1369] },
    { 0x13e20, &_symbol_string_table[1384] },
    { 0x13e40, &_symbol_string_table[1399] },
    { 0x13f80, &_symbol_string_table[1406] },
    { 0x14070, &_symbol_string_table[1413] },
    { 0x141b0, &_symbol_string_table[1421] },
    { 0x14200, &_symbol_string_table[1428] },
    { 0x142c0, &_symbol_string_table[1471] },
    { 0x143f0, &_symbol_string_table[1508] },
    { 0x14480, &_symbol_string_table[1526] },
    { 0x14500, &_symbol_string_table[1547] },
    { 0x14530, &_symbol_string_table[1567] },
    { 0x145d0, &_symbol_string_table[1588] },
    { 0x14770, &_symbol_string_table[1611] },
    { 0x147d0, &_symbol_string_table[1632] },
    { 0x14840, &_symbol_string_table[1653] },
    { 0x14920, &_symbol_string_table[1676] },
    { 0x14950, &_symbol_string_table[1689] },
    { 0x149d0, &_symbol_string_table[1705] },
    { 0x14aa0, &_symbol_string_table[1715] },
    { 0x14ac0, &_symbol_string_table[1730] },
    { 0x14b30, &_symbol_string_table[1745] },
    { 0x14ee0, &_symbol_string_table[1762] },
    { 0x15270, &_symbol_string_table[1780] },
    { 0x15510, &_symbol_string_table[1791] },
    { 0x155f0, &_symbol_string_table[1808] },
    { 0x15620, &_symbol_string_table[1818] },
    { 0x15660, &_symbol_string_table[1834] },
    { 0x156f0, &_symbol_string_table[1846] },
    { 0x15780, &_symbol_string_table[1863] },
    { 0x157c0, &_symbol_string_table[1881] },
    { 0x15850, &_symbol_string_table[1908] },
    { 0x15a90, &_symbol_string_table[1925] },
    { 0x15b70, &_symbol_string_table[1945] },
    { 0x15d80, &_symbol_string_table[1963] },
    { 0x15df0, &_symbol_string_table[1981] },
    { 0x15e30, &_symbol_string_table[1994] },
    { 0x15eb0, &_symbol_string_table[2007] },
    { 0x15f30, &_symbol_string_table[2024] },
    { 0x15f60, &_symbol_string_table[2038] },
    { 0x15f90, &_symbol_string_table[2052] },
    { 0x15fc0, &_symbol_string_table[2077] },
    { 0x160d0, &_symbol_string_table[2097] },
    { 0x16280, &_symbol_string_table[2118] },
    { 0x16360, &_symbol_string_table[2132] },
    { 0x163a0, &_symbol_string_table[2149] },
    { 0x16420, &_symbol_string_table[2166] },
    { 0x164a0, &_symbol_string_table[2187] },
    { 0x164d0, &_symbol_string_table[2216] },
    { 0x164e0, &_symbol_string_table[2220] },
    { 0x164f0, &_symbol_string_table[2225] },
    { 0x165d0, &_symbol_string_table[2234] },
    { 0x16630, &_symbol_string_table[2247] },
    { 0x166a0, &_symbol_string_table[2263] },
    { 0x16710, &_symbol_string_table[2278] },
    { 0x16770, &_symbol_string_table[2296] },
    { 0x167c0, &_symbol_string_table[2312] },
    { 0x16810, &_symbol_string_table[2327] },
    { 0x16860, &_symbol_string_table[2345] },
    { 0x16970, &_symbol_string_table[2356] },
    { 0x169a0, &_symbol_string_table[2372] },
    { 0x16a00, &_symbol_string_table[2385] },
    { 0x16a30, &_symbol_string_table[2404] },
    { 0x16b00, &_symbol_string_table[2424] },
    { 0x16bd0, &_symbol_string_table[2440] },
    { 0x16dd0, &_symbol_string_table[2449] },
    { 0x16f50, &_symbol_string_table[2469] },
    { 0x17040, &_symbol_string_table[2490] },
    { 0x17250, &_symbol_string_table[2504] },
    { 0x17340, &_symbol_string_table[2522] },
    { 0x175c0, &_symbol_string_table[2535] },
    { 0x17980, &_symbol_string_table[2548] },
    { 0x179d0, &_symbol_string_table[2564] },
    { 0x17a20, &_symbol_string_table[2577] },
    { 0x17a50, &_symbol_string_table[2601] },
    { 0x17ae0, &_symbol_string_table[2617] },
    { 0x17b10, &_symbol_string_table[2628] },
    { 0x17b80, &_symbol_string_table[2638] },
    { 0x18740, &_symbol_string_table[2657] },
    { 0x18790, &_symbol_string_table[2665] },
    { 0x187a0, &_symbol_string_table[2673] },
    { 0x18980, &_symbol_string_table[2680] },
    { 0x189b0, &_symbol_string_table[2688] },
    { 0x18b60, &_symbol_string_table[2696] },
    { 0x18ba0, &_symbol_string_table[2701] },
    { 0x18be0, &_symbol_string_table[2713] },
    { 0x18cf0, &_symbol_string_table[2718] },
    { 0x18db0, &_symbol_string_table[2724] },
    { 0x18eb0, &_symbol_string_table[2736] },
    { 0x18f80, &_symbol_string_table[2744] },
    { 0x18fb0, &_symbol_string_table[2751] },
    { 0x18ff0, &_symbol_string_table[2759] },
    { 0x19020, &_symbol_string_table[2766] },
    { 0x19060, &_symbol_string_table[2774] },
    { 0x190b0, &_symbol_string_table[2781] },
    { 0x190f0, &_symbol_string_table[2789] },
    { 0x191a0, &_symbol_string_table[2800] },
    { 0x19210, &_symbol_string_table[2812] },
    { 0x19250, &_symbol_string_table[2819] },
    { 0x19280, &_symbol_string_table[2827] },
    { 0x19300, &_symbol_string_table[2834] },
    { 0x19360, &_symbol_string_table[2842] },
    { 0x193c0, &_symbol_string_table[2849] },
    { 0x19440, &_symbol_string_table[2857] },
    { 0x19550, &_symbol_string_table[2866] },
    { 0x19580, &_symbol_string_table[2873] },
    { 0x195a0, &_symbol_string_table[2881] },
    { 0x195b0, &_symbol_string_table[2900] },
    { 0x195f0, &_symbol_string_table[2917] },
    { 0x19640, &_symbol_string_table[2925] },
    { 0x19670, &_symbol_string_table[2937] },
    { 0x196a0, &_symbol_string_table[2949] },
    { 0x19700, &_symbol_string_table[2958] },
    { 0x19780, &_symbol_string_table[2968] },
    { 0x19850, &_symbol_string_table[2977] },
    { 0x198d0, &_symbol_string_table[2990] },
    { 0x199c0, &_symbol_string_table[2999] },
    { 0x19ba0, &_symbol_string_table[3009] },
    { 0x19c00, &_symbol_string_table[3018] },
    { 0x19c40, &_symbol_string_table[3033] },
    { 0x19c70, &_symbol_string_table[3055] },
    { 0x19cd0, &_symbol_string_table[3069] },
    { 0x19e20, &_symbol_string_table[3093] },
    { 0x19e60, &_symbol_string_table[3103] },
    { 0x19e70, &_symbol_string_table[3112] },
    { 0x19fe0, &_symbol_string_table[3121] },
    { 0x1a2e0, &_symbol_string_table[3139] },
    { 0x1a700, &_symbol_string_table[3152] },
    { 0x1a740, &_symbol_string_table[3163] },
    { 0x1abf0, &_symbol_string_table[3173] },
    { 0x1ac00, &_symbol_string_table[3187] },
    { 0x1ad70, &_symbol_string_table[3210] },
    { 0x1af00, &_symbol_string_table[3235] },
    { 0x1b000, &_symbol_string_table[3253] },
    { 0x1b180, &_symbol_string_table[3271] },
    { 0x1b200, &_symbol_string_table[3297] },
    { 0x1c800, &_symbol_string_table[3321] },
    { 0x1c804, &_symbol_string_table[3337] },
    { 0x1c810, &_symbol_string_table[3355] },
    { 0x1c820, &_symbol_string_table[3376] },
    { 0x1c860, &_symbol_string_table[3376] },
    { 0x1c8a0, &_symbol_string_table[3386] },
    { 0x1c9a0, &_symbol_string_table[3402] },
    { 0x1ca40, &_symbol_string_table[3416] },
    { 0x1ca80, &_symbol_string_table[3430] },
    { 0x1cac0, &_symbol_string_table[3448] },
    { 0x1cb00, &_symbol_string_table[3463] },
    { 0x1cb40, &_symbol_string_table[3476] },
    { 0x1cb80, &_symbol_string_table[3490] },
    { 0x1cba0, &_symbol_string_table[3512] },
    { 0x1cba0, &_symbol_string_table[3521] },
    { 0x1cda0, &_symbol_string_table[3533] },
    { 0x1cdc0, &_symbol_string_table[3545] },
    { 0x1cfc0, &_symbol_string_table[3552] },
    { 0x1cfe0, &_symbol_string_table[3570] },
    { 0x1d060, &_symbol_string_table[3589] },
    { 0x1d160, &_symbol_string_table[3599] },
    { 0x1d960, &_symbol_string_table[3615] },
    { 0x1e960, &_symbol_string_table[3619] },
    { 0x1e964, &_symbol_string_table[3633] },
    { 0x1e980, &_symbol_string_table[3652] },
    { 0x1f580, &_symbol_string_table[3667] },
    { 0x1f590, &_symbol_string_table[3685] },
    { 0x1f5c0, &_symbol_string_table[3707] },
    { 0x1f5e0, &_symbol_string_table[3734] },
    { 0x1f700, &_symbol_string_table[3744] },
    { 0x1f820, &_symbol_string_table[3754] },
    { 0x1f821, &_symbol_string_table[3769] },
    { 0x1f822, &_symbol_string_table[3782] },
    { 0x1f840, &_symbol_string_table[3799] },
    { 0x1f948, &_symbol_string_table[3809] },
    { 0x1f950, &_symbol_string_table[3824] },
    { 0x1f958, &_symbol_string_table[3840] },
    { 0x1f960, &_symbol_string_table[3852] },
    { 0x1f968, &_symbol_string_table[3868] },
    { 0x1f970, &_symbol_string_table[3886] },
    { 0x1f978, &_symbol_string_table[3905] },
    { 0x1f980, &_symbol_string_table[3926] },
    { 0x1f988, &_symbol_string_table[3948] },
    { 0x1f9a0, &_symbol_string_table[3968] },
    { 0x1f9c0, &_symbol_string_table[3984] },
    { 0x1f9e0, &_symbol_string_table[3991] },
    { 0x1fa00, &_symbol_string_table[4004] },
    { 0x1fab0, &_symbol_string_table[4018] },
    { 0x1fac0, &_symbol_string_table[4034] },
    { 0x207c0, &_symbol_string_table[4045] },
    { 0, NULL }
};

__attribute__((section(".rodata")))
const symbol_entry_t _symbol_table_end[] = {
    { 0, NULL }
};

/* Text section bounds */
const uintptr_t _symbol_text_start = 0x10000;
const uintptr_t _symbol_text_end = 0x1aee6;
