/* Auto-generated by scripts/extract_symbols.py */
/* DO NOT EDIT */

#include "stacktrace/symbol.h"

/* String table for symbol names */
__attribute__((section(".rodata")))
const char _symbol_string_table[] =
    "kernel_start\0"
    "halt_loop\0"
    "kernel_main\0"
    "kernel_init\0"
    "isr0\0"
    "isr1\0"
    "isr2\0"
    "isr3\0"
    "isr4\0"
    "isr5\0"
    "isr6\0"
    "isr7\0"
    "isr8\0"
    "isr9\0"
    "isr10\0"
    "isr11\0"
    "isr12\0"
    "isr13\0"
    "isr14\0"
    "isr15\0"
    "isr16\0"
    "isr17\0"
    "isr18\0"
    "isr19\0"
    "isr20\0"
    "isr21\0"
    "isr22\0"
    "isr23\0"
    "isr24\0"
    "isr25\0"
    "isr26\0"
    "isr27\0"
    "isr28\0"
    "isr29\0"
    "isr30\0"
    "isr31\0"
    "irq0\0"
    "irq1\0"
    "irq2\0"
    "irq3\0"
    "irq4\0"
    "irq5\0"
    "irq6\0"
    "irq7\0"
    "irq8\0"
    "irq9\0"
    "irq10\0"
    "irq11\0"
    "irq12\0"
    "irq13\0"
    "irq14\0"
    "irq15\0"
    "interrupt_common\0"
    "idt_load\0"
    "kvprintf\0"
    "kprintf\0"
    "klog_set_level\0"
    "klog_get_level\0"
    "klog_level_name\0"
    "klog_log\0"
    "klog_init\0"
    "klog_get_backend_ops\0"
    "klog_set_default_backend\0"
    "klog_get_default_backend\0"
    "klog_register_backend\0"
    "serial_is_ready\0"
    "serial_process\0"
    "klog_serial_backend_init\0"
    "klog_serial_backend_get_ops\0"
    "bootAllWelcomes\0"
    "vga_display_welcome\0"
    "serial_display_welcome\0"
    "idt_init\0"
    "idt_set_gate\0"
    "idt_register_handler\0"
    "idt_get_exception_name\0"
    "irq_register_handler\0"
    "irq_unregister_handler\0"
    "interrupt_handler\0"
    "interrupt_init\0"
    "interrupt_finalize\0"
    "memset\0"
    "memcpy\0"
    "memmove\0"
    "memcmp\0"
    "vga_update_hardware_cursor_position.part.0\0"
    "vga_scroll.part.0.constprop.0.isra.0\0"
    "vga_enable_cursor\0"
    "vga_set_cursor_color\0"
    "vga_soft_cursor_get\0"
    "vga_soft_cursor_init\0"
    "vga_soft_cursor_enable\0"
    "vga_soft_cursor_hide\0"
    "vga_soft_cursor_draw\0"
    "vga_soft_cursor_update\0"
    "vga_instance\0"
    "system_vga_init\0"
    "vga_clear\0"
    "vga_get_cursor\0"
    "vga_set_cursor\0"
    "vga_print_string\0"
    "vga_print_stringn\0"
    "vga_scroll\0"
    "set_vga_property\0"
    "vga_delay\0"
    "vga_put_char_at\0"
    "serial_init\0"
    "sync_serial_puts\0"
    "serial_color_ansi\0"
    "serial_color_for_log_level\0"
    "uart_irq_handler\0"
    "uart_init_intr_mode\0"
    "async_serial_putc\0"
    "async_serial_puts\0"
    "uart_haschar\0"
    "uart_getchar\0"
    "uart_try_getchar\0"
    "uart_set_echo\0"
    "uart_get_echo\0"
    "uart_get_interrupt_count\0"
    "uart_dump_registers\0"
    "keyboard_irq_handler\0"
    "keyboard_init\0"
    "keyboard_haschar\0"
    "keyboard_getchar\0"
    "keyboard_try_getchar\0"
    "keyboard_get_interrupt_count\0"
    "inb\0"
    "outb\0"
    "pic_init\0"
    "pic_send_eoi\0"
    "pic_disable_irq\0"
    "pic_enable_irq\0"
    "pic_is_irq_masked\0"
    "pic_disable_all\0"
    "pic_enable_all\0"
    "timer_irq_handler\0"
    "timer_init\0"
    "timer_get_ticks\0"
    "timer_mdelay\0"
    "timer_set_callback\0"
    "timer_set_frequency\0"
    "rtc_irq_handler\0"
    "rtc_init\0"
    "rtc_enable_periodic\0"
    "rtc_disable_periodic\0"
    "rtc_set_alarm\0"
    "rtc_disable_alarm\0"
    "rtc_get_time\0"
    "rtc_set_time\0"
    "rtc_is_updating\0"
    "rtc_is_valid\0"
    "rtc_get_interrupt_count\0"
    "rtc_format_time\0"
    "kvsnprintf\0"
    "ksnprintf\0"
    "klog_format_string\0"
    "e820_get_stats.part.0\0"
    "e820_init\0"
    "e820_get_detect_method\0"
    "e820_get_detect_method_name\0"
    "e820_get_entry_count\0"
    "e820_get_entry\0"
    "e820_get_stats\0"
    "e820_dump_map\0"
    "e820_is_range_usable\0"
    "e820_find_usable_range\0"
    "e820_get_type_name\0"
    "e820_get_usable_memory_above\0"
    "e820_count_usable_regions\0"
    "format_size.part.0\0"
    "bytes_to_mb\0"
    "bytes_to_kb\0"
    "mb_to_bytes\0"
    "kb_to_bytes\0"
    "pages_to_bytes\0"
    "bytes_to_pages\0"
    "align_up\0"
    "align_down\0"
    "is_aligned\0"
    "format_size\0"
    "format_size_ex\0"
    "format_size_unit\0"
    "mem_summary_init\0"
    "mem_summary_add_region\0"
    "mem_summary_calculate_mb\0"
    "mem_summary_calculate_pages\0"
    "mem_summary_dump\0"
    "ranges_overlap\0"
    "range_contains\0"
    "pframe_init\0"
    "pframe_alloc\0"
    "pframe_alloc_n\0"
    "pframe_free\0"
    "pframe_free_n\0"
    "pframe_get_stats\0"
    "pframe_dump\0"
    "pframe_is_allocated\0"
    "pframe_get_total_frames\0"
    "pframe_get_free_frames\0"
    "pf_init\0"
    "pf_parse_error_code\0"
    "pf_handler\0"
    "pf_handle_cow\0"
    "pf_register_cow_region\0"
    "pf_handle_demand_page\0"
    "dump_pte_flags\0"
    "page_init\0"
    "page_get_pml4\0"
    "page_create_table\0"
    "page_free_table\0"
    "page_map_page\0"
    "page_unmap_page\0"
    "page_query\0"
    "page_virt_to_phys\0"
    "page_map_range\0"
    "page_unmap_range\0"
    "page_flush_cache\0"
    "page_dump_mapping\0"
    "page_dump_pml4\0"
    "add_region\0"
    "vmm_init\0"
    "vmm_get_kernel_pml4\0"
    "vmm_map_physical\0"
    "vmm_unmap_physical\0"
    "vmm_free_pages\0"
    "vmm_alloc_pages\0"
    "vmm_alloc_pages_at\0"
    "vmm_get_stats\0"
    "vmm_dump\0"
    "vmm_create_user_space\0"
    "vmm_destroy_user_space\0"
    "vmm_map_to_user\0"
    "vmm_dump_memory_map\0"
    "validate_block\0"
    "insert_to_free_list\0"
    "coalesce_block\0"
    "expand_heap\0"
    "heap_init\0"
    "kmalloc\0"
    "kfree\0"
    "krealloc\0"
    "kmalloc_aligned\0"
    "heap_get_stats\0"
    "heap_dump\0"
    "run_possible_demos\0"
    "ccos_assert_impl\0"
    "assert_backend_to_vga\0"
    "assert_failed_action\0"
    "isspace\0"
    "isdigit\0"
    "strtol\0"
    "strtoll\0"
    "strtoul\0"
    "atoi\0"
    "reverse_str\0"
    "itoa\0"
    "uitoa\0"
    "itoa_signed\0"
    "uitoa64\0"
    "__stack_chk_fail\0"
    "strlen\0"
    "strnlen\0"
    "strcpy\0"
    "strncpy\0"
    "strcmp\0"
    "strncmp\0"
    "strcasecmp\0"
    "strncasecmp\0"
    "strchr\0"
    "strrchr\0"
    "strstr\0"
    "strpbrk\0"
    "strspn\0"
    "strcspn\0"
    "strtok_r\0"
    "strtok\0"
    "tolower\0"
    "bitmap_init\0"
    "bitmap_set\0"
    "bitmap_clear\0"
    "bitmap_test\0"
    "bitmap_flip\0"
    "bitmap_set_range\0"
    "bitmap_clear_range\0"
    "bitmap_find_first_zero\0"
    "bitmap_find_first_set\0"
    "bitmap_find_next_zero\0"
    "bitmap_find_next_set\0"
    "bitmap_equal\0"
    "bitmap_copy\0"
    "bitmap_and\0"
    "bitmap_or\0"
    "bitmap_xor\0"
    "bitmap_andnot\0"
    "bitmap_complement\0"
    "bitmap_to_string\0"
    "bitmap_weight\0"
    "bitmap_full\0"
    "bitmap_empty\0"
    "vga_clear_screen\0"
    "cmd_cls\0"
    "vga_getchar\0"
    "vga_haschar\0"
    "vga_putc\0"
    "cmd_ticks\0"
    "cmd_time\0"
    "cmd_keyboard\0"
    "cmd_goto\0"
    "cmd_color\0"
    "vga_puts\0"
    "vga_shell_init\0"
    "vga_shell_backend_get\0"
    "vga_shell_run\0"
    "vga_shell_init_commands\0"
    "cmd_clear\0"
    "cmd_exit\0"
    "cmd_help\0"
    "shell_step.part.0\0"
    "shell_create\0"
    "shell_step\0"
    "shell_run\0"
    "shell_destroy\0"
    "shell_register_command\0"
    "shell_unregister_command\0"
    "isr_handler_table\0"
    "irq_handler_table\0"
    "scancode_to_ascii_shifted\0"
    "scancode_to_ascii_table\0"
    "__func__.0\0"
    "__func__.1\0"
    "__func__.2\0"
    "__func__.3\0"
    "__func__.4\0"
    "__func__.5\0"
    "__func__.6\0"
    "__func__.7\0"
    "__func__.8\0"
    "__func__.9\0"
    "__func__.10\0"
    "uart_echo_enabled\0"
    "s_detect_method\0"
    "s_kernel_virt_hint\0"
    "g_serial_backend_ops\0"
    "CCOS_LOGO\0"
    "exception_names\0"
    "g_ansi_colors\0"
    "uart_irq_desc\0"
    "keyboard_irq_desc\0"
    "timer_irq_desc\0"
    "rtc_irq_desc\0"
    "g_vga_backend\0"
    "_GLOBAL_OFFSET_TABLE_\0"
    "buffer.0\0"
    "__bss_start\0"
    "g_log_level\0"
    "buffer\0"
    "g_default_backend\0"
    "g_backend_registry\0"
    "irq_table\0"
    "custom_handlers\0"
    "idt\0"
    "soft_cursor_state\0"
    "internal_vga_instance\0"
    "uart_intr_mode_initialized\0"
    "rx_buffer\0"
    "tx_buffer\0"
    "kb_initialized\0"
    "kb_caps_lock\0"
    "kb_shift_pressed\0"
    "kb_buffer\0"
    "timer_callback\0"
    "timer_frequency\0"
    "timer_ticks\0"
    "rtc_binary_mode\0"
    "rtc_alarm_context\0"
    "rtc_alarm_callback\0"
    "rtc_periodic_context\0"
    "rtc_periodic_callback\0"
    "rtc_interrupt_count\0"
    "g_format_buffer\0"
    "s_initialized\0"
    "s_e820_entry_count\0"
    "s_e820_entries\0"
    "s_pframe_state\0"
    "s_pf_stats\0"
    "s_direct_map_established\0"
    "s_kernel_pml4\0"
    "s_region_count\0"
    "s_regions\0"
    "s_stats\0"
    "s_heap\0"
    "save.0\0"
    "registered.0\0"
    "g_shell_ctx.1\0"
    "g_command_count\0"
    "g_commands\0"
    "s_frame_bitmap_storage\0"
    "__bss_end\0"
;

/* Symbol table entries */
__attribute__((section(".rodata")))
const symbol_entry_t _symbol_table_start[] = {
    { 0x10000, &_symbol_string_table[0] },
    { 0x1003d, &_symbol_string_table[13] },
    { 0x10050, &_symbol_string_table[23] },
    { 0x100d0, &_symbol_string_table[35] },
    { 0x102e0, &_symbol_string_table[47] },
    { 0x102eb, &_symbol_string_table[52] },
    { 0x102f6, &_symbol_string_table[57] },
    { 0x10301, &_symbol_string_table[62] },
    { 0x1030c, &_symbol_string_table[67] },
    { 0x10317, &_symbol_string_table[72] },
    { 0x10322, &_symbol_string_table[77] },
    { 0x1032d, &_symbol_string_table[82] },
    { 0x10338, &_symbol_string_table[87] },
    { 0x10341, &_symbol_string_table[92] },
    { 0x1034c, &_symbol_string_table[97] },
    { 0x10355, &_symbol_string_table[103] },
    { 0x1035e, &_symbol_string_table[109] },
    { 0x10367, &_symbol_string_table[115] },
    { 0x10370, &_symbol_string_table[121] },
    { 0x10379, &_symbol_string_table[127] },
    { 0x10384, &_symbol_string_table[133] },
    { 0x1038f, &_symbol_string_table[139] },
    { 0x1039a, &_symbol_string_table[145] },
    { 0x103a5, &_symbol_string_table[151] },
    { 0x103b0, &_symbol_string_table[157] },
    { 0x103bb, &_symbol_string_table[163] },
    { 0x103c6, &_symbol_string_table[169] },
    { 0x103d1, &_symbol_string_table[175] },
    { 0x103dc, &_symbol_string_table[181] },
    { 0x103e7, &_symbol_string_table[187] },
    { 0x103f2, &_symbol_string_table[193] },
    { 0x103fd, &_symbol_string_table[199] },
    { 0x10408, &_symbol_string_table[205] },
    { 0x10413, &_symbol_string_table[211] },
    { 0x1041e, &_symbol_string_table[217] },
    { 0x10429, &_symbol_string_table[223] },
    { 0x10434, &_symbol_string_table[229] },
    { 0x1043c, &_symbol_string_table[234] },
    { 0x10444, &_symbol_string_table[239] },
    { 0x1044c, &_symbol_string_table[244] },
    { 0x10454, &_symbol_string_table[249] },
    { 0x1045c, &_symbol_string_table[254] },
    { 0x10464, &_symbol_string_table[259] },
    { 0x1046c, &_symbol_string_table[264] },
    { 0x10474, &_symbol_string_table[269] },
    { 0x1047c, &_symbol_string_table[274] },
    { 0x10484, &_symbol_string_table[279] },
    { 0x1048c, &_symbol_string_table[285] },
    { 0x10494, &_symbol_string_table[291] },
    { 0x1049c, &_symbol_string_table[297] },
    { 0x104a4, &_symbol_string_table[303] },
    { 0x104ac, &_symbol_string_table[309] },
    { 0x104b4, &_symbol_string_table[315] },
    { 0x1057e, &_symbol_string_table[332] },
    { 0x10590, &_symbol_string_table[341] },
    { 0x10630, &_symbol_string_table[350] },
    { 0x10700, &_symbol_string_table[358] },
    { 0x10730, &_symbol_string_table[373] },
    { 0x10760, &_symbol_string_table[388] },
    { 0x107f0, &_symbol_string_table[404] },
    { 0x10a30, &_symbol_string_table[413] },
    { 0x10be0, &_symbol_string_table[423] },
    { 0x10c60, &_symbol_string_table[444] },
    { 0x10c90, &_symbol_string_table[469] },
    { 0x10cc0, &_symbol_string_table[494] },
    { 0x10e40, &_symbol_string_table[516] },
    { 0x10e50, &_symbol_string_table[532] },
    { 0x10ec0, &_symbol_string_table[547] },
    { 0x10ef0, &_symbol_string_table[572] },
    { 0x10f20, &_symbol_string_table[600] },
    { 0x10fa0, &_symbol_string_table[616] },
    { 0x113d0, &_symbol_string_table[636] },
    { 0x11d50, &_symbol_string_table[659] },
    { 0x122a0, &_symbol_string_table[668] },
    { 0x12320, &_symbol_string_table[681] },
    { 0x12350, &_symbol_string_table[702] },
    { 0x12390, &_symbol_string_table[725] },
    { 0x12510, &_symbol_string_table[746] },
    { 0x125f0, &_symbol_string_table[769] },
    { 0x128c0, &_symbol_string_table[787] },
    { 0x12970, &_symbol_string_table[802] },
    { 0x12a00, &_symbol_string_table[821] },
    { 0x12b40, &_symbol_string_table[828] },
    { 0x12c30, &_symbol_string_table[835] },
    { 0x12d70, &_symbol_string_table[843] },
    { 0x12dc0, &_symbol_string_table[850] },
    { 0x12e80, &_symbol_string_table[893] },
    { 0x12fb0, &_symbol_string_table[930] },
    { 0x13040, &_symbol_string_table[948] },
    { 0x130c0, &_symbol_string_table[969] },
    { 0x130f0, &_symbol_string_table[989] },
    { 0x13190, &_symbol_string_table[1010] },
    { 0x13330, &_symbol_string_table[1033] },
    { 0x13390, &_symbol_string_table[1054] },
    { 0x13400, &_symbol_string_table[1075] },
    { 0x134e0, &_symbol_string_table[1098] },
    { 0x13510, &_symbol_string_table[1111] },
    { 0x13590, &_symbol_string_table[1127] },
    { 0x13660, &_symbol_string_table[1137] },
    { 0x13680, &_symbol_string_table[1152] },
    { 0x136f0, &_symbol_string_table[1167] },
    { 0x13aa0, &_symbol_string_table[1184] },
    { 0x13e30, &_symbol_string_table[1202] },
    { 0x140d0, &_symbol_string_table[1213] },
    { 0x141b0, &_symbol_string_table[1230] },
    { 0x141e0, &_symbol_string_table[1240] },
    { 0x14220, &_symbol_string_table[1256] },
    { 0x142b0, &_symbol_string_table[1268] },
    { 0x14340, &_symbol_string_table[1285] },
    { 0x14380, &_symbol_string_table[1303] },
    { 0x14410, &_symbol_string_table[1330] },
    { 0x14650, &_symbol_string_table[1347] },
    { 0x14730, &_symbol_string_table[1367] },
    { 0x14940, &_symbol_string_table[1385] },
    { 0x149b0, &_symbol_string_table[1403] },
    { 0x149f0, &_symbol_string_table[1416] },
    { 0x14a70, &_symbol_string_table[1429] },
    { 0x14af0, &_symbol_string_table[1446] },
    { 0x14b20, &_symbol_string_table[1460] },
    { 0x14b50, &_symbol_string_table[1474] },
    { 0x14b80, &_symbol_string_table[1499] },
    { 0x14c90, &_symbol_string_table[1519] },
    { 0x14e40, &_symbol_string_table[1540] },
    { 0x14f20, &_symbol_string_table[1554] },
    { 0x14f60, &_symbol_string_table[1571] },
    { 0x14fe0, &_symbol_string_table[1588] },
    { 0x15060, &_symbol_string_table[1609] },
    { 0x15090, &_symbol_string_table[1638] },
    { 0x150a0, &_symbol_string_table[1642] },
    { 0x150b0, &_symbol_string_table[1647] },
    { 0x15190, &_symbol_string_table[1656] },
    { 0x151f0, &_symbol_string_table[1669] },
    { 0x15260, &_symbol_string_table[1685] },
    { 0x152d0, &_symbol_string_table[1700] },
    { 0x15330, &_symbol_string_table[1718] },
    { 0x15380, &_symbol_string_table[1734] },
    { 0x153d0, &_symbol_string_table[1749] },
    { 0x15420, &_symbol_string_table[1767] },
    { 0x15530, &_symbol_string_table[1778] },
    { 0x15560, &_symbol_string_table[1794] },
    { 0x155c0, &_symbol_string_table[1807] },
    { 0x155f0, &_symbol_string_table[1826] },
    { 0x156c0, &_symbol_string_table[1846] },
    { 0x15790, &_symbol_string_table[1862] },
    { 0x15990, &_symbol_string_table[1871] },
    { 0x15b10, &_symbol_string_table[1891] },
    { 0x15c00, &_symbol_string_table[1912] },
    { 0x15e10, &_symbol_string_table[1926] },
    { 0x15f00, &_symbol_string_table[1944] },
    { 0x16180, &_symbol_string_table[1957] },
    { 0x16540, &_symbol_string_table[1970] },
    { 0x16590, &_symbol_string_table[1986] },
    { 0x165e0, &_symbol_string_table[1999] },
    { 0x16610, &_symbol_string_table[2023] },
    { 0x166a0, &_symbol_string_table[2039] },
    { 0x166d0, &_symbol_string_table[2050] },
    { 0x16740, &_symbol_string_table[2060] },
    { 0x17300, &_symbol_string_table[2079] },
    { 0x173c0, &_symbol_string_table[2101] },
    { 0x17670, &_symbol_string_table[2111] },
    { 0x176a0, &_symbol_string_table[2134] },
    { 0x17700, &_symbol_string_table[2162] },
    { 0x17730, &_symbol_string_table[2183] },
    { 0x177d0, &_symbol_string_table[2198] },
    { 0x17820, &_symbol_string_table[2213] },
    { 0x17bc0, &_symbol_string_table[2227] },
    { 0x17c90, &_symbol_string_table[2248] },
    { 0x17d90, &_symbol_string_table[2271] },
    { 0x17e20, &_symbol_string_table[2290] },
    { 0x17eb0, &_symbol_string_table[2319] },
    { 0x17f20, &_symbol_string_table[2345] },
    { 0x18000, &_symbol_string_table[2364] },
    { 0x18010, &_symbol_string_table[2376] },
    { 0x18020, &_symbol_string_table[2388] },
    { 0x18030, &_symbol_string_table[2400] },
    { 0x18040, &_symbol_string_table[2412] },
    { 0x18050, &_symbol_string_table[2427] },
    { 0x18060, &_symbol_string_table[2442] },
    { 0x18080, &_symbol_string_table[2451] },
    { 0x18090, &_symbol_string_table[2462] },
    { 0x180b0, &_symbol_string_table[2473] },
    { 0x181a0, &_symbol_string_table[2485] },
    { 0x182d0, &_symbol_string_table[2500] },
    { 0x183f0, &_symbol_string_table[2517] },
    { 0x18430, &_symbol_string_table[2534] },
    { 0x18450, &_symbol_string_table[2557] },
    { 0x18470, &_symbol_string_table[2582] },
    { 0x184a0, &_symbol_string_table[2610] },
    { 0x18680, &_symbol_string_table[2627] },
    { 0x186a0, &_symbol_string_table[2642] },
    { 0x186b0, &_symbol_string_table[2657] },
    { 0x18d70, &_symbol_string_table[2669] },
    { 0x18ed0, &_symbol_string_table[2682] },
    { 0x19120, &_symbol_string_table[2697] },
    { 0x19250, &_symbol_string_table[2709] },
    { 0x19360, &_symbol_string_table[2723] },
    { 0x19400, &_symbol_string_table[2740] },
    { 0x195a0, &_symbol_string_table[2752] },
    { 0x19600, &_symbol_string_table[2772] },
    { 0x19630, &_symbol_string_table[2796] },
    { 0x19690, &_symbol_string_table[2819] },
    { 0x19740, &_symbol_string_table[2827] },
    { 0x19790, &_symbol_string_table[2847] },
    { 0x19c60, &_symbol_string_table[2858] },
    { 0x19c90, &_symbol_string_table[2872] },
    { 0x19ca0, &_symbol_string_table[2895] },
    { 0x19d00, &_symbol_string_table[2917] },
    { 0x19f30, &_symbol_string_table[2932] },
    { 0x1a130, &_symbol_string_table[2942] },
    { 0x1a1b0, &_symbol_string_table[2956] },
    { 0x1a2d0, &_symbol_string_table[2974] },
    { 0x1a390, &_symbol_string_table[2990] },
    { 0x1a950, &_symbol_string_table[3004] },
    { 0x1aac0, &_symbol_string_table[3020] },
    { 0x1acf0, &_symbol_string_table[3031] },
    { 0x1add0, &_symbol_string_table[3049] },
    { 0x1af80, &_symbol_string_table[3064] },
    { 0x1b040, &_symbol_string_table[3081] },
    { 0x1b0a0, &_symbol_string_table[3098] },
    { 0x1b5b0, &_symbol_string_table[3116] },
    { 0x1b7c0, &_symbol_string_table[3131] },
    { 0x1b8b0, &_symbol_string_table[3142] },
    { 0x1baf0, &_symbol_string_table[3151] },
    { 0x1bb70, &_symbol_string_table[3171] },
    { 0x1bd70, &_symbol_string_table[3188] },
    { 0x1bea0, &_symbol_string_table[3207] },
    { 0x1c040, &_symbol_string_table[3222] },
    { 0x1c600, &_symbol_string_table[3238] },
    { 0x1caf0, &_symbol_string_table[3257] },
    { 0x1cbd0, &_symbol_string_table[3271] },
    { 0x1cdc0, &_symbol_string_table[3280] },
    { 0x1cf20, &_symbol_string_table[3302] },
    { 0x1d1f0, &_symbol_string_table[3325] },
    { 0x1d390, &_symbol_string_table[3341] },
    { 0x1dc80, &_symbol_string_table[3361] },
    { 0x1dd60, &_symbol_string_table[3376] },
    { 0x1dea0, &_symbol_string_table[3396] },
    { 0x1e140, &_symbol_string_table[3411] },
    { 0x1e2a0, &_symbol_string_table[3423] },
    { 0x1e430, &_symbol_string_table[3433] },
    { 0x1e7f0, &_symbol_string_table[3441] },
    { 0x1e9d0, &_symbol_string_table[3447] },
    { 0x1ecd0, &_symbol_string_table[3456] },
    { 0x1ee50, &_symbol_string_table[3472] },
    { 0x1f070, &_symbol_string_table[3487] },
    { 0x1f320, &_symbol_string_table[3497] },
    { 0x1f360, &_symbol_string_table[3516] },
    { 0x1f3c0, &_symbol_string_table[3533] },
    { 0x1f7f0, &_symbol_string_table[3555] },
    { 0x1f840, &_symbol_string_table[3576] },
    { 0x1f890, &_symbol_string_table[3584] },
    { 0x1f8a0, &_symbol_string_table[3592] },
    { 0x1fa80, &_symbol_string_table[3599] },
    { 0x1fab0, &_symbol_string_table[3607] },
    { 0x1fc60, &_symbol_string_table[3615] },
    { 0x1fca0, &_symbol_string_table[3620] },
    { 0x1fce0, &_symbol_string_table[3632] },
    { 0x1fdf0, &_symbol_string_table[3637] },
    { 0x1feb0, &_symbol_string_table[3643] },
    { 0x1ffb0, &_symbol_string_table[3655] },
    { 0x20080, &_symbol_string_table[3663] },
    { 0x20100, &_symbol_string_table[3680] },
    { 0x20130, &_symbol_string_table[3687] },
    { 0x20170, &_symbol_string_table[3695] },
    { 0x201a0, &_symbol_string_table[3702] },
    { 0x201e0, &_symbol_string_table[3710] },
    { 0x20230, &_symbol_string_table[3717] },
    { 0x20270, &_symbol_string_table[3725] },
    { 0x20320, &_symbol_string_table[3736] },
    { 0x20390, &_symbol_string_table[3748] },
    { 0x203d0, &_symbol_string_table[3755] },
    { 0x20400, &_symbol_string_table[3763] },
    { 0x20480, &_symbol_string_table[3770] },
    { 0x204e0, &_symbol_string_table[3778] },
    { 0x20540, &_symbol_string_table[3785] },
    { 0x205c0, &_symbol_string_table[3793] },
    { 0x206d0, &_symbol_string_table[3802] },
    { 0x20700, &_symbol_string_table[3809] },
    { 0x20720, &_symbol_string_table[3817] },
    { 0x20760, &_symbol_string_table[3829] },
    { 0x207f0, &_symbol_string_table[3840] },
    { 0x20880, &_symbol_string_table[3853] },
    { 0x20910, &_symbol_string_table[3865] },
    { 0x209a0, &_symbol_string_table[3877] },
    { 0x20a80, &_symbol_string_table[3894] },
    { 0x20b60, &_symbol_string_table[3913] },
    { 0x20c40, &_symbol_string_table[3936] },
    { 0x20d20, &_symbol_string_table[3958] },
    { 0x20e00, &_symbol_string_table[3980] },
    { 0x20ee0, &_symbol_string_table[4001] },
    { 0x20f50, &_symbol_string_table[4014] },
    { 0x20f90, &_symbol_string_table[4026] },
    { 0x20fe0, &_symbol_string_table[4037] },
    { 0x21020, &_symbol_string_table[4047] },
    { 0x21060, &_symbol_string_table[4058] },
    { 0x210a0, &_symbol_string_table[4072] },
    { 0x210e0, &_symbol_string_table[4090] },
    { 0x211c0, &_symbol_string_table[4107] },
    { 0x21260, &_symbol_string_table[4121] },
    { 0x21310, &_symbol_string_table[4133] },
    { 0x213c0, &_symbol_string_table[4146] },
    { 0x21400, &_symbol_string_table[4163] },
    { 0x21450, &_symbol_string_table[4171] },
    { 0x21480, &_symbol_string_table[4183] },
    { 0x214b0, &_symbol_string_table[4195] },
    { 0x21510, &_symbol_string_table[4204] },
    { 0x21590, &_symbol_string_table[4214] },
    { 0x21660, &_symbol_string_table[4223] },
    { 0x216e0, &_symbol_string_table[4236] },
    { 0x217d0, &_symbol_string_table[4245] },
    { 0x219b0, &_symbol_string_table[4255] },
    { 0x21a10, &_symbol_string_table[4264] },
    { 0x21a50, &_symbol_string_table[4279] },
    { 0x21a80, &_symbol_string_table[4301] },
    { 0x21ae0, &_symbol_string_table[4315] },
    { 0x21c20, &_symbol_string_table[4339] },
    { 0x21c60, &_symbol_string_table[4349] },
    { 0x21c70, &_symbol_string_table[4358] },
    { 0x21de0, &_symbol_string_table[4367] },
    { 0x220e0, &_symbol_string_table[4385] },
    { 0x22500, &_symbol_string_table[4398] },
    { 0x22540, &_symbol_string_table[4409] },
    { 0x229f0, &_symbol_string_table[4419] },
    { 0x22a00, &_symbol_string_table[4433] },
    { 0x22b70, &_symbol_string_table[4456] },
    { 0x22d00, &_symbol_string_table[4481] },
    { 0x22e00, &_symbol_string_table[4499] },
    { 0x22f20, &_symbol_string_table[4517] },
    { 0x22fa0, &_symbol_string_table[4543] },
    { 0x23290, &_symbol_string_table[4567] },
    { 0x232a0, &_symbol_string_table[4578] },
    { 0x232b0, &_symbol_string_table[4567] },
    { 0x232c0, &_symbol_string_table[4567] },
    { 0x232d0, &_symbol_string_table[4578] },
    { 0x232f0, &_symbol_string_table[4589] },
    { 0x23308, &_symbol_string_table[4600] },
    { 0x23320, &_symbol_string_table[4611] },
    { 0x23338, &_symbol_string_table[4622] },
    { 0x23350, &_symbol_string_table[4633] },
    { 0x23360, &_symbol_string_table[4644] },
    { 0x23370, &_symbol_string_table[4655] },
    { 0x23380, &_symbol_string_table[4666] },
    { 0x23398, &_symbol_string_table[4677] },
    { 0x233b0, &_symbol_string_table[4567] },
    { 0x233c0, &_symbol_string_table[4578] },
    { 0x233e0, &_symbol_string_table[4589] },
    { 0x233f8, &_symbol_string_table[4600] },
    { 0x23408, &_symbol_string_table[4611] },
    { 0x23420, &_symbol_string_table[4622] },
    { 0x23440, &_symbol_string_table[4633] },
    { 0x23450, &_symbol_string_table[4644] },
    { 0x23470, &_symbol_string_table[4655] },
    { 0x23490, &_symbol_string_table[4666] },
    { 0x234b0, &_symbol_string_table[4567] },
    { 0x234c8, &_symbol_string_table[4578] },
    { 0x234e0, &_symbol_string_table[4589] },
    { 0x234f8, &_symbol_string_table[4567] },
    { 0x23508, &_symbol_string_table[4578] },
    { 0x23518, &_symbol_string_table[4589] },
    { 0x23528, &_symbol_string_table[4600] },
    { 0x265a0, &_symbol_string_table[4689] },
    { 0x265a4, &_symbol_string_table[4707] },
    { 0x265a8, &_symbol_string_table[4723] },
    { 0x265b0, &_symbol_string_table[4742] },
    { 0x265c0, &_symbol_string_table[4763] },
    { 0x26600, &_symbol_string_table[4763] },
    { 0x26640, &_symbol_string_table[4773] },
    { 0x26740, &_symbol_string_table[4789] },
    { 0x267e0, &_symbol_string_table[4803] },
    { 0x26820, &_symbol_string_table[4817] },
    { 0x26860, &_symbol_string_table[4835] },
    { 0x268a0, &_symbol_string_table[4850] },
    { 0x268e0, &_symbol_string_table[4863] },
    { 0x26920, &_symbol_string_table[4877] },
    { 0x26940, &_symbol_string_table[4899] },
    { 0x26940, &_symbol_string_table[4908] },
    { 0x26b40, &_symbol_string_table[4920] },
    { 0x26b60, &_symbol_string_table[4932] },
    { 0x26d60, &_symbol_string_table[4939] },
    { 0x26d80, &_symbol_string_table[4957] },
    { 0x26e00, &_symbol_string_table[4976] },
    { 0x26f00, &_symbol_string_table[4986] },
    { 0x27700, &_symbol_string_table[5002] },
    { 0x28700, &_symbol_string_table[5006] },
    { 0x28710, &_symbol_string_table[5024] },
    { 0x28740, &_symbol_string_table[5046] },
    { 0x28760, &_symbol_string_table[5073] },
    { 0x28880, &_symbol_string_table[5083] },
    { 0x289a0, &_symbol_string_table[5093] },
    { 0x289a1, &_symbol_string_table[5108] },
    { 0x289a2, &_symbol_string_table[5121] },
    { 0x289c0, &_symbol_string_table[5138] },
    { 0x28ac8, &_symbol_string_table[5148] },
    { 0x28ad0, &_symbol_string_table[5163] },
    { 0x28ad8, &_symbol_string_table[5179] },
    { 0x28ae0, &_symbol_string_table[5191] },
    { 0x28ae8, &_symbol_string_table[5207] },
    { 0x28af0, &_symbol_string_table[5225] },
    { 0x28af8, &_symbol_string_table[5244] },
    { 0x28b00, &_symbol_string_table[5265] },
    { 0x28b08, &_symbol_string_table[5287] },
    { 0x28b20, &_symbol_string_table[5307] },
    { 0x28b40, &_symbol_string_table[5323] },
    { 0x28b44, &_symbol_string_table[5337] },
    { 0x28b60, &_symbol_string_table[5356] },
    { 0x29760, &_symbol_string_table[5371] },
    { 0x297a0, &_symbol_string_table[5386] },
    { 0x297e0, &_symbol_string_table[5323] },
    { 0x297e4, &_symbol_string_table[5397] },
    { 0x297e5, &_symbol_string_table[5323] },
    { 0x297e8, &_symbol_string_table[5422] },
    { 0x29800, &_symbol_string_table[5323] },
    { 0x29804, &_symbol_string_table[5436] },
    { 0x29820, &_symbol_string_table[5451] },
    { 0x2a820, &_symbol_string_table[5461] },
    { 0x2a848, &_symbol_string_table[5422] },
    { 0x2a860, &_symbol_string_table[5469] },
    { 0x2a8d0, &_symbol_string_table[5476] },
    { 0x2a8e0, &_symbol_string_table[5483] },
    { 0x2a900, &_symbol_string_table[5496] },
    { 0x2a9b0, &_symbol_string_table[5510] },
    { 0x2a9c0, &_symbol_string_table[5526] },
    { 0x2b6c0, &_symbol_string_table[5537] },
    { 0x2b6c0, &_symbol_string_table[5560] },
    { 0, NULL }
};

__attribute__((section(".rodata")))
const symbol_entry_t _symbol_table_end[] = {
    { 0, NULL }
};

/* Text section bounds */
const uintptr_t _symbol_text_start = 0x10000;
const uintptr_t _symbol_text_end = 0x22ce6;
