#!/usr/bin/env python3
"""
Extract symbol table from kernel ELF for stack trace symbol resolution.

Generates C files with symbol table data that can be linked into the kernel.
"""

import argparse
import subprocess
import sys
from pathlib import Path


def readelf_get_symbols(elf_path):
    """Get symbols from ELF using readelf."""
    try:
        result = subprocess.run(
            ['readelf', '-s', '-W', str(elf_path)],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"Error running readelf: {e}", file=sys.stderr)
        return None
    except FileNotFoundError:
        print("Error: readelf not found. Install binutils.", file=sys.stderr)
        return None


def parse_symbols(readelf_output):
    """Parse readelf output to extract symbol information."""
    symbols = []

    for line in readelf_output.split('\n'):
        # Skip header and empty lines
        if not line or 'Num:' in line or 'Symbol table' in line:
            continue

        # Parse the readelf output format
        # Num:    Value          Size Type    Bind   Vis      Ndx Name
        parts = line.split()
        if len(parts) < 8:
            continue

        try:
            # Get value (address)
            value = int(parts[1], 16)

            # Get type and binding
            sym_type = parts[3]
            sym_bind = parts[4] if len(parts) > 4 else ''

            # Include FUNC, NOTYPE (for labels like halt_loop)
            # Skip SECTION and FILE
            if sym_type in ('SECTION', 'FILE'):
                continue

            # Get section index - we only want code sections (section 1 is .text)
            ndx = parts[6]
            if ndx == 'UND' or ndx == 'ABS':
                continue

            # Get symbol name (might have spaces)
            name = ' '.join(parts[7:])

            # Filter out unwanted symbols
            if name.startswith('__') and name.endswith('__'):
                continue
            if name in ('_init', '_fini'):
                continue
            # Skip unnamed symbols
            if not name or name.startswith('$'):
                continue

            symbols.append((value, name))

        except (ValueError, IndexError):
            continue

    return symbols


def generate_symbol_files(symbols, text_start, text_end, output_dir):
    """Generate C source files with symbol table data."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Sort symbols by address
    symbols.sort(key=lambda x: x[0])

    # Generate symbols.c
    symbols_c = output_dir / 'symbols.c'
    with open(symbols_c, 'w') as f:
        f.write("/* Auto-generated by scripts/extract_symbols.py */\n")
        f.write("/* DO NOT EDIT */\n\n")
        f.write('#include "stacktrace/symbol.h"\n\n')

        # String table
        f.write("/* String table for symbol names */\n")
        f.write("__attribute__((section(\".rodata\")))\n")
        f.write("const char _symbol_string_table[] =\n")

        string_offsets = {}
        current_offset = 0

        for addr, name in symbols:
            if name not in string_offsets:
                # Escape special characters in name
                escaped_name = name.encode('utf-8').decode('unicode_escape').encode('unicode_escape').decode('ascii')
                escaped_name = escaped_name.replace('"', '\\"')
                f.write(f'    "{escaped_name}\\0"\n')
                string_offsets[name] = current_offset
                current_offset += len(name) + 1

        f.write(";\n\n")

        # Symbol table entries
        f.write("/* Symbol table entries */\n")
        f.write("__attribute__((section(\".rodata\")))\n")
        f.write("const symbol_entry_t _symbol_table_start[] = {\n")

        for addr, name in symbols:
            # Calculate offset in string table
            offset = 0
            for n, o in string_offsets.items():
                if n == name:
                    offset = o
                    break

            f.write(f"    {{ 0x{addr:x}, &_symbol_string_table[{offset}] }},\n")

        # Add terminator to the symbol table
        f.write("    { 0, NULL }\n")  # Terminator marker
        f.write("};\n\n")
        f.write("__attribute__((section(\".rodata\")))\n")
        f.write("const symbol_entry_t _symbol_table_end[] = {\n")
        f.write("    { 0, NULL }\n")
        f.write("};\n\n")

        # Text section bounds
        f.write("/* Text section bounds */\n")
        f.write(f"const uintptr_t _symbol_text_start = 0x{text_start:x};\n")
        f.write(f"const uintptr_t _symbol_text_end = 0x{text_end:x};\n")

    print(f"Generated {symbols_c}")

    # Generate symbols.h (for reference, not included)
    symbols_h = output_dir / 'symbols.h'
    with open(symbols_h, 'w') as f:
        f.write("/* Auto-generated by scripts/extract_symbols.py */\n")
        f.write("/* Symbol count: {} */\n".format(len(symbols)))
        f.write("/* Text range: 0x{:x} - 0x{:x} */\n".format(text_start, text_end))

    print(f"Generated {symbols_h}")
    print(f"Total symbols: {len(symbols)}")


def get_text_section_bounds(elf_path):
    """Get the start and end of .text section from ELF."""
    try:
        result = subprocess.run(
            ['readelf', '-S', str(elf_path)],
            capture_output=True,
            text=True,
            check=True
        )

        text_start = None
        text_size = None

        lines = result.stdout.split('\n')
        for i, line in enumerate(lines):
            if '.text' in line and 'PROGBITS' in line:
                # Combine current line with next line (readelf splits section info)
                parts = line.split()
                # Format: [Nr] Name Type Address Off
                # Parts can be: ['[', '1]', '.text', 'PROGBITS', '0000000000010000', '00001000']
                # or: ['[', '1]', '.text', 'PROGBITS', '0000000000010000', ...]
                if len(parts) >= 5:
                    # Address is at index 4 (after Name, Type, PROGBITS)
                    try:
                        text_start = int(parts[4], 16)
                    except ValueError:
                        # Maybe different format, try next position
                        if len(parts) >= 6:
                            text_start = int(parts[5], 16)

                # Get size from next line
                if i + 1 < len(lines):
                    next_parts = lines[i + 1].split()
                    if len(next_parts) >= 1:
                        try:
                            text_size = int(next_parts[0], 16)
                        except ValueError:
                            pass
                break

        if text_start is not None and text_size is not None:
            return text_start, text_start + text_size

    except (subprocess.CalledProcessError, FileNotFoundError, ValueError) as e:
        print(f"Debug: Error reading section: {e}", file=sys.stderr)

    # Fallback to known values
    print("Warning: Could not read .text section, using defaults", file=sys.stderr)
    return 0x10000, 0x20000


def main():
    parser = argparse.ArgumentParser(description='Extract symbols from kernel ELF')
    parser.add_argument('elf', help='Path to kernel ELF file')
    parser.add_argument('-o', '--output', default='build/kernel/stacktrace',
                       help='Output directory (default: build/kernel/stacktrace)')
    args = parser.parse_args()

    # Get symbol information
    readelf_output = readelf_get_symbols(args.elf)
    if readelf_output is None:
        sys.exit(1)

    symbols = parse_symbols(readelf_output)
    if not symbols:
        print("No symbols found!", file=sys.stderr)
        sys.exit(1)

    # Get text section bounds
    text_start, text_end = get_text_section_bounds(args.elf)

    # Generate output files
    generate_symbol_files(symbols, text_start, text_end, args.output)


if __name__ == '__main__':
    main()
