# ==============================================================================
# CCOS Kernel Configuration Generator
# ==============================================================================
# This script generates boot_config.inc with actual kernel size information
# Usage: cmake -DKERNEL_BIN=file.bin -DBOOTLOADER_BIN=file.bin -DOUTPUT_FILE=output.inc -P GenerateKernelSize.cmake
# ==============================================================================

# Parse arguments
set(KERNEL_BIN "${KERNEL_BIN}" CACHE FILEPATH "Path to kernel.bin")
set(BOOTLOADER_BIN "${BOOTLOADER_BIN}" CACHE FILEPATH "Path to bootloader.bin")
set(OUTPUT_FILE "${OUTPUT_FILE}" CACHE FILEPATH "Output .inc file")

if(NOT EXISTS "${KERNEL_BIN}")
    message(FATAL_ERROR "Kernel binary not found: ${KERNEL_BIN}")
endif()

if(NOT EXISTS "${BOOTLOADER_BIN}")
    message(FATAL_ERROR "Bootloader binary not found: ${BOOTLOADER_BIN}")
endif()

# Get kernel size in bytes
file(SIZE "${KERNEL_BIN}" KERNEL_SIZE_BYTES)

# Get bootloader size in bytes
file(SIZE "${BOOTLOADER_BIN}" BOOTLOADER_SIZE_BYTES)

# Calculate sectors (round up)
math(EXPR KERNEL_SECTORS "(${KERNEL_SIZE_BYTES} + 511) / 512")
math(EXPR BOOTLOADER_SECTORS "(${BOOTLOADER_SIZE_BYTES} + 511) / 512")

# Maximum kernel size: 64MB
set(MAX_KERNEL_SIZE_MB 64)
math(EXPR MAX_SECTORS "${MAX_KERNEL_SIZE_MB} * 1024 * 1024 / 512")

if(KERNEL_SECTORS GREATER MAX_SECTORS)
    message(FATAL_ERROR "Kernel too large: ${KERNEL_SIZE_BYTES} bytes (${KERNEL_SECTORS} sectors), max ${MAX_KERNEL_SIZE_MB}MB (${MAX_SECTORS} sectors)")
endif()

# Kernel LBA start (after bootloader)
set(KERNEL_LBA_START ${BOOTLOADER_SECTORS})
math(EXPR KERNEL_LBA_ZERO "${KERNEL_LBA_START} - 1")

# CHS calculation (standard geometry: 63 sectors/track, 16 heads)
set(SECTORS_PER_TRACK 63)
set(HEADS 16)

math(EXPR CHS_CYLINDER "${KERNEL_LBA_ZERO} / (${SECTORS_PER_TRACK} * ${HEADS})")
math(EXPR CHS_HEAD "(${KERNEL_LBA_ZERO} / ${SECTORS_PER_TRACK}) % ${HEADS}")
math(EXPR CHS_SECTOR "(${KERNEL_LBA_ZERO} % ${SECTORS_PER_TRACK}) + 1")

# Memory layout calculations
set(STAGE2_START_HEX "0x7E00")
set(STAGE2_START 32256)
math(EXPR STAGE2_END "${STAGE2_START} + ${BOOTLOADER_SECTORS} * 512")
set(KERNEL_LOAD_ADDR_HEX "0x10000")
set(KERNEL_LOAD_ADDR 65536)

# Calculate memory gap
math(EXPR MEMORY_GAP "${KERNEL_LOAD_ADDR} - ${STAGE2_END}")

# Memory layout (ensure 1-sector gap from Stage 2)
set(KERNEL_LOAD_SEGMENT "0x1000")
set(KERNEL_LOAD_OFFSET "0x0000")

# ============================================================================
# Print disk layout information
# ============================================================================
message(STATUS "")
message(STATUS "============================================================")
message(STATUS "  DISK LAYOUT CALCULATION")
message(STATUS "============================================================")
message(STATUS "Bootloader:")
message(STATUS "  Size: ${BOOTLOADER_SIZE_BYTES} bytes = ${BOOTLOADER_SECTORS} sectors")
message(STATUS "  Location: Sector 1-${BOOTLOADER_SECTORS} (LBA 0-${KERNEL_LBA_START}-1)")
message(STATUS "")
message(STATUS "Kernel:")
message(STATUS "  Size: ${KERNEL_SIZE_BYTES} bytes = ${KERNEL_SECTORS} sectors")
message(STATUS "  Location: Sector ${KERNEL_LBA_START}+ (LBA ${KERNEL_LBA_START}+)")
message(STATUS "  Load address: ${KERNEL_LOAD_ADDR_HEX}")
message(STATUS "")
message(STATUS "CHS Parameters (for fallback):")
message(STATUS "  Cylinder: ${CHS_CYLINDER}")
message(STATUS "  Head: ${CHS_HEAD}")
message(STATUS "  Sector: ${CHS_SECTOR} (1-based)")
message(STATUS "")
message(STATUS "Memory Layout:")
message(STATUS "  Stage 2 ends at:  0x${STAGE2_END}")
message(STATUS "  Kernel starts at: ${KERNEL_LOAD_ADDR_HEX}")
math(EXPR MEMORY_GAP_SECTORS "${MEMORY_GAP} / 512")
message(STATUS "  Memory gap: ${MEMORY_GAP} bytes (${MEMORY_GAP_SECTORS} sectors)")
if(MEMORY_GAP LESS 512)
    message(WARNING "  WARNING: Memory gap < 512 bytes! Risk of overlap.")
else()
    message(STATUS "  ✓ Memory gap sufficient for safe loading")
endif()
message(STATUS "============================================================")
message(STATUS "")

# Check for memory overlap
if(STAGE2_END GREATER KERNEL_LOAD_ADDR)
    message(FATAL_ERROR "MEMORY OVERLAP DETECTED: Stage 2 (0x${STAGE2_END}) overlaps kernel (${KERNEL_LOAD_ADDR_HEX})")
endif()

# ============================================================================
# Generate the .inc file
# ==============================================================================
set(CONFIG_CONTENT "")
list(APPEND CONFIG_CONTENT "; ==============================================================================")
list(APPEND CONFIG_CONTENT "; CCOS Bootloader Configuration")
list(APPEND CONFIG_CONTENT "; ==============================================================================")
list(APPEND CONFIG_CONTENT "; This file is AUTO-GENERATED by CMake during build")
list(APPEND CONFIG_CONTENT "; Generated from: ${KERNEL_BIN} (${KERNEL_SIZE_BYTES} bytes)")
list(APPEND CONFIG_CONTENT ";              : ${BOOTLOADER_BIN} (${BOOTLOADER_SIZE_BYTES} bytes)")
list(APPEND CONFIG_CONTENT "; DO NOT EDIT MANUALLY - Changes will be overwritten")
list(APPEND CONFIG_CONTENT "; ==============================================================================")
list(APPEND CONFIG_CONTENT "")
list(APPEND CONFIG_CONTENT "; Kernel disk location (LBA/CHS)")
list(APPEND CONFIG_CONTENT "%define KERNEL_LBA_START          ${KERNEL_LBA_START}")
list(APPEND CONFIG_CONTENT "%define KERNEL_SECTOR_COUNT       ${KERNEL_SECTORS}")
list(APPEND CONFIG_CONTENT "")
list(APPEND CONFIG_CONTENT "; Memory layout (ensure 1-sector gap from Stage 2)")
list(APPEND CONFIG_CONTENT "%define KERNEL_LOAD_SEGMENT       ${KERNEL_LOAD_SEGMENT}")
list(APPEND CONFIG_CONTENT "%define KERNEL_LOAD_OFFSET        ${KERNEL_LOAD_OFFSET}")
list(APPEND CONFIG_CONTENT "")
list(APPEND CONFIG_CONTENT "; Bootloader size info")
list(APPEND CONFIG_CONTENT "%define BOOTLOADER_SECTORS        ${BOOTLOADER_SECTORS}")
list(APPEND CONFIG_CONTENT "")
list(APPEND CONFIG_CONTENT "; Memory gap: 1 sector between bootloader and kernel")
list(APPEND CONFIG_CONTENT "; Stage 2 ends at:  0x7E00 + (${BOOTLOADER_SECTORS} sectors * 512) = 0x${STAGE2_END}")
list(APPEND CONFIG_CONTENT "; Kernel starts at: 0x10000 (safe gap of ${MEMORY_GAP} bytes)")
list(APPEND CONFIG_CONTENT "")
list(APPEND CONFIG_CONTENT "; Maximum kernel size: ${MAX_KERNEL_SIZE_MB}MB = ${MAX_SECTORS} sectors")
list(APPEND CONFIG_CONTENT "%define KERNEL_MAX_SECTORS        ${MAX_SECTORS}")
list(APPEND CONFIG_CONTENT "")
list(APPEND CONFIG_CONTENT "; =============================================================================")
list(APPEND CONFIG_CONTENT "; CHS Geometry (for CHS fallback)")
list(APPEND CONFIG_CONTENT "; =============================================================================")
list(APPEND CONFIG_CONTENT "; Standard geometry: ${SECTORS_PER_TRACK} sectors/track, ${HEADS} heads")
list(APPEND CONFIG_CONTENT "%define SECTORS_PER_TRACK         ${SECTORS_PER_TRACK}")
list(APPEND CONFIG_CONTENT "%define HEADS                     ${HEADS}")
list(APPEND CONFIG_CONTENT "")
list(APPEND CONFIG_CONTENT "; Kernel CHS start (LBA=${KERNEL_LBA_ZERO})")
list(APPEND CONFIG_CONTENT "; Cylinder = ${KERNEL_LBA_ZERO} / (${SECTORS_PER_TRACK} * ${HEADS}) = ${CHS_CYLINDER}")
list(APPEND CONFIG_CONTENT "; Head     = (${KERNEL_LBA_ZERO} / ${SECTORS_PER_TRACK}) % ${HEADS} = ${CHS_HEAD}")
list(APPEND CONFIG_CONTENT "; Sector   = (${KERNEL_LBA_ZERO} % ${SECTORS_PER_TRACK}) + 1 = ${CHS_SECTOR}")
list(APPEND CONFIG_CONTENT "%define KERNEL_CHS_CYLINDER       ${CHS_CYLINDER}")
list(APPEND CONFIG_CONTENT "%define KERNEL_CHS_HEAD           ${CHS_HEAD}")
list(APPEND CONFIG_CONTENT "%define KERNEL_CHS_SECTOR         ${CHS_SECTOR}")

# Write the content
file(WRITE "${OUTPUT_FILE}" "")
foreach(LINE ${CONFIG_CONTENT})
    file(APPEND "${OUTPUT_FILE}" "${LINE}\n")
endforeach()

message(STATUS "Generated: ${OUTPUT_FILE}")
