# ==============================================================================
# CCOS Kernel Configuration Generator
# ==============================================================================
# This script generates boot_config.inc with actual kernel size information
# Usage: cmake -DKERNEL_BIN=file.bin -DOUTPUT_FILE=output.inc -P GenerateKernelSize.cmake
# ==============================================================================

# Parse arguments
set(KERNEL_BIN "${KERNEL_BIN}" CACHE FILEPATH "Path to kernel.bin")
set(OUTPUT_FILE "${OUTPUT_FILE}" CACHE FILEPATH "Output .inc file")
set(BOOTLOADER_SECTORS "${BOOTLOADER_SECTORS}" CACHE STRING "Number of bootloader sectors")

if(NOT EXISTS "${KERNEL_BIN}")
    message(FATAL_ERROR "Kernel binary not found: ${KERNEL_BIN}")
endif()

# Get kernel size in bytes
file(SIZE "${KERNEL_BIN}" KERNEL_SIZE_BYTES)

# Calculate sectors (round up)
math(EXPR KERNEL_SECTORS "(${KERNEL_SIZE_BYTES} + 511) / 512")

# Maximum kernel size: 64MB
set(MAX_KERNEL_SIZE_MB 64)
math(EXPR MAX_SECTORS "${MAX_KERNEL_SIZE_MB} * 1024 * 1024 / 512")

if(KERNEL_SECTORS GREATER MAX_SECTORS)
    message(FATAL_ERROR "Kernel too large: ${KERNEL_SIZE_BYTES} bytes (${KERNEL_SECTORS} sectors), max ${MAX_KERNEL_SIZE_MB}MB (${MAX_SECTORS} sectors)")
endif()

# Kernel LBA start (after bootloader)
set(KERNEL_LBA_START ${BOOTLOADER_SECTORS})
math(EXPR KERNEL_LBA_ZERO "${KERNEL_LBA_START} - 1")

# CHS calculation (standard geometry: 63 sectors/track, 16 heads)
set(SECTORS_PER_TRACK 63)
set(HEADS 16)

math(EXPR CHS_CYLINDER "${KERNEL_LBA_ZERO} / (${SECTORS_PER_TRACK} * ${HEADS})")
math(EXPR CHS_HEAD "(${KERNEL_LBA_ZERO} / ${SECTORS_PER_TRACK}) % ${HEADS}")
math(EXPR CHS_SECTOR "(${KERNEL_LBA_ZERO} % ${SECTORS_PER_TRACK}) + 1")

# Memory layout (ensure 1-sector gap from Stage 2)
# Stage 2 ends at: 0x7E00 + (bootloader_sectors * 512)
# We load kernel at 0x10000 for safety
set(KERNEL_LOAD_SEGMENT "0x1000")
set(KERNEL_LOAD_OFFSET "0x0000")

# Generate the .inc file
file(WRITE "${OUTPUT_FILE}"; ==============================================================================
; CCOS Bootloader Configuration
; ==============================================================================
; This file is AUTO-GENERATED by CMake during build
; Generated from: ${KERNEL_BIN}
; Kernel size: ${KERNEL_SIZE_BYTES} bytes (${KERNEL_SECTORS} sectors)
; DO NOT EDIT MANUALLY - Changes will be overwritten
; ==============================================================================

; Kernel disk location (LBA/CHS)
%define KERNEL_LBA_START          ${KERNEL_LBA_START}           ; Kernel starts at sector ${KERNEL_LBA_START} (1-based)
%define KERNEL_SECTOR_COUNT       ${KERNEL_SECTORS}             ; Actual kernel size in sectors

; Memory layout (ensure 1-sector gap from Stage 2)
%define KERNEL_LOAD_SEGMENT       ${KERNEL_LOAD_SEGMENT}      ; ES:BX = ${KERNEL_LOAD_SEGMENT}:${KERNEL_LOAD_OFFSET} = 0x10000
%define KERNEL_LOAD_OFFSET        ${KERNEL_LOAD_OFFSET}

; Bootloader size info
%define BOOTLOADER_SECTORS        ${BOOTLOADER_SECTORS}           ; Stage1(1) + Stage2(${BOOTLOADER_SECTORS})

; Memory gap: 1 sector between bootloader and kernel
; Stage 2 ends at:  0x7E00 + (${BOOTLOADER_SECTORS} sectors * 512) = 0x7E00 + 0x${BOOTLOADER_HEX_SIZE}
; Kernel starts at: 0x10000 (safe gap)

; Maximum kernel size: ${MAX_KERNEL_SIZE_MB}MB = ${MAX_SECTORS} sectors
%define KERNEL_MAX_SECTORS        ${MAX_SECTORS}

; ============================================================================
; CHS Geometry (for CHS fallback)
; ============================================================================
; Standard geometry: ${SECTORS_PER_TRACK} sectors/track, ${HEADS} heads
; LBA to CHS formula:
;   Cylinder = LBA / (sectors_per_track * heads)
;   Head     = (LBA / sectors_per_track) % heads
;   Sector   = (LBA % sectors_per_track) + 1

%define SECTORS_PER_TRACK         ${SECTORS_PER_TRACK}
%define HEADS                     ${HEADS}

; Kernel CHS start (LBA=${KERNEL_LBA_ZERO})
; Cylinder = ${KERNEL_LBA_ZERO} / (${SECTORS_PER_TRACK} * ${HEADS}) = ${CHS_CYLINDER}
; Head     = (${KERNEL_LBA_ZERO} / ${SECTORS_PER_TRACK}) % ${HEADS} = ${CHS_HEAD}
; Sector   = (${KERNEL_LBA_ZERO} % ${SECTORS_PER_TRACK}) + 1 = ${CHS_SECTOR}
%define KERNEL_CHS_CYLINDER       ${CHS_CYLINDER}
%define KERNEL_CHS_HEAD           ${CHS_HEAD}
%define KERNEL_CHS_SECTOR         ${CHS_SECTOR}
)

message(STATUS "Generated boot configuration:")
message(STATUS "  Kernel: ${KERNEL_SIZE_BYTES} bytes = ${KERNEL_SECTORS} sectors")
message(STATUS "  LBA start: ${KERNEL_LBA_START} (sector ${KERNEL_LBA_START}, 1-based)")
message(STATUS "  CHS: C=${CHS_CYLINDER} H=${CHS_HEAD} S=${CHS_SECTOR}")
message(STATUS "  Load address: 0x10000")
message(STATUS "  Output: ${OUTPUT_FILE}")
